

<div dir="rtl" style="text-align: right;">

## Pandas Course الدرس الأول 1
 </div>



<div dir="rtl" style="text-align: right;">

## قراءة الملفات واستكشاف البيانات باستخدام Pandas

 </div>



<div dir="rtl" style="text-align: right;">

#### تنصيب مكتبة Pandas

In [ ]:
# pip install pandas

<div dir="rtl" style="text-align: right;">
 استيراد المكتبة
 </div>

In [1]:
import pandas as pd

<div dir="rtl" style="text-align: right;">

### 1- قراءة ملفات  CSV
 </div>

<div dir="rtl" style="text-align: right;">


 </div>

In [2]:
df1 = pd.read_csv(r"D:\Pandas\Pandas_Course\countries of the world.csv")

<div dir="rtl" style="text-align: right;">

1.1 عرض البيانات مع تحديد عدد الصفوف 

 </div>

In [3]:
df1.head(10)

              Country                               Region
0        Afghanistan         ASIA (EX. NEAR EAST)
1            Albania   EASTERN EUROPE
2            Algeria   NORTHERN AFRICA
3     American Samoa   OCEANIA
4            Andorra   WESTERN EUROPE
5             Angola   SUB-SAHARAN AFRICA
6           Anguilla               LATIN AMER. & CARIB
7  Antigua & Barbuda               LATIN AMER. & CARIB
8          Argentina               LATIN AMER. & CARIB
9            Armenia                  C.W. OF IND. STATES

<div dir="rtl" style="text-align: right;">

1.2 عرض بيانات الملفات التي لا تحتوي على اسماء الأعمدة 

 </div>

In [6]:
df1 = pd.read_csv(r"D:\Pandas\Pandas_Course\without_header_name.csv",
    sep = ';',
    header = None,
    names = ['ID_Code', 'Age', 'Status', 'Reagon', 'Score', 'Year'],)


df1.head()

  ID_Code  Age Status Reagon  Score  Year
0     A12   45    Yes  North    3.5  2024
1     B09   33     No   East    2.1  2023
2     C88   27    Yes  South    4.0  2025
3     D77   52     No   West    1.9  2022
4     E41   29    Yes  North    3.2  2024

<div dir="rtl" style="text-align: right;">

### 2- قراءة الملفات بشكل عام مع تحديد الفاصلة  
 </div>

In [7]:
df2 = pd.read_table(r"D:\Pandas\Pandas_Course\syria_data.txt", sep= ';')

df2.head()

   ID     Name  Age  Grade      City Country
0   1      Ali   15     10  Damascus   Syria
1   2     Sara   14      9    Aleppo   Syria
2   3     Omar   16     11      Homs   Syria
3   4     Lina   15     10   Latakia   Syria
4   5  Youssef   14      9      Hama   Syria

<div dir="rtl" style="text-align: right;">
3- قراءة ملفات JSON 

</div>

In [8]:
df3 = pd.read_json(r"D:\Pandas\Pandas_Course\json_sample.json")
df3

,12 Strong,A Fantastic Woman (Una Mujer Fantástica),All The Money In The World,Bilal: A New Breed Of Hero,Call Me By Your Name,Darkest Hour,Den Of Thieves,Ferdinand,Fifty Shades Freed,Film Stars Don'T Die In Liverpool,...,The 15:17 To Paris,The Commuter,The Disaster Artist,The Greatest Showman,The Insult (L'Insulte),The Post,The Shape Of Water,"Three Billboards Outside Ebbing, Missouri",Till The End Of The World,Winchester
0,"{'Genre': 'Action', 'Gross': '$453,173', 'IMDB...","{'popcornscore': 83, 'rating': 'R', 'tomatosco...","{'popcornscore': 71, 'rating': 'R', 'tomatosco...","{'popcornscore': 91, 'rating': 'PG13', 'tomato...","{'popcornscore': 87, 'rating': 'R', 'tomatosco...","{'popcornscore': 84, 'rating': 'PG13', 'tomato...","{'Genre': 'Action', 'Gross': '$491,898', 'IMDB...","{'popcornscore': 49, 'rating': 'PG', 'tomatosc...","{'Genre': 'Drama', 'Gross': 'unknown', 'IMDB M...","{'popcornscore': 69, 'rating': 'R', 'tomatosco...",...,"{'Genre': 'Drama', 'Gross': 'unknown', 'IMDB M...","{'popcornscore': 48, 'rating': 'PG13', 'tomato...","{'popcornscore': 89, 'rating': 'R', 'tomatosco...","{'Genre': 'Biography', 'Gross': '$627,248', 'I...","{'popcornscore': 86, 'rating': 'R', 'tomatosco...","{'Genre': 'Biography', 'Gross': '$463,228', 'I...","{'Genre': 'Adventure', 'Gross': '$448,287', 'I...","{'popcornscore': 87, 'rating': 'R', 'tomatosco...","{'popcornscore': -1, 'rating': 'NR', 'tomatosc...","{'Genre': 'Biography', 'Gross': '$696,786', 'I..."

<div dir="rtl" style="text-align: right;">
4- قراءة ملفات Excel
 </div>

<div dir="rtl" style="text-align: right;">
4.1. بدون تحديد اسم الصفحة
 </div>

In [9]:
df4 = pd.read_excel(r"D:\Pandas\Pandas_Course\world_population1.xlsx")
df4.head()

,Rank,CCA3,Country,Capital,Continent,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (kmÂ²),Density (per kmÂ²),Growth Rate,World Population Percentage
0,36,AFG,Afghanistan,Kabul,Asia,41128771,38972230,33753499,28189672,19542982,10694796,12486631,10752971,652230,63.0587,1.0257,0.52
1,138,ALB,Albania,Tirana,Europe,2842321,2866849,2882481,2913399,3182021,3295066,2941651,2324731,28748,98.8702,0.9957,0.04
2,34,DZA,Algeria,Algiers,Africa,44903225,43451666,39543154,35856344,30774621,25518074,18739378,13795915,2381741,18.8531,1.0164,0.56
3,213,ASM,American Samoa,Pago Pago,Oceania,44273,46189,51368,54849,58230,47818,32886,27075,199,222.4774,0.9831,0.00
4,203,AND,Andorra,Andorra la Vella,Europe,79824,77700,71746,71519,66097,53569,35611,19860,468,170.5641,1.0100,0.00

<div dir="rtl" style="text-align: right;">
4.2. مع تحديد اسم الصفحة
 </div>

In [14]:
df4 = pd.read_excel(r"D:\Pandas\Pandas_Course\world_population2.xlsx", sheet_name = 'Sheet1')
df4.head()

   Rank CCA3         Country           Capital
0    36  AFG     Afghanistan             Kabul
1   138  ALB         Albania            Tirana
2    34  DZA         Algeria           Algiers
3   213  ASM  American Samoa         Pago Pago
4   203  AND         Andorra  Andorra la Vella

<div dir="rtl" style="text-align: right;">
4.3. التعامل مع الصفوف الفارغة في الأعلى
 </div>

In [16]:
df4 = pd.read_excel(r"D:\Pandas\Pandas_Course\world_population3.xlsx")
df4.head(12)

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,Rank,CCA3,Country,Capital,Continent,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (kmÂ²),Density (per kmÂ²),Growth Rate,World Population Percentage
6,NaN,NaN,NaN,36,AFG,Afghanistan,Kabul,Asia,41128771,38972230,33753499,28189672,19542982,10694796,12486631,10752971,652230,63.0587,1.0257,0.52
7,NaN,NaN,NaN,138,ALB,Albania,Tirana,Europe,2842321,2866849,2882481,2913399,3182021,3295066,2941651,2324731,28748,98.8702,0.9957,0.04
8,NaN,NaN,NaN,34,DZA,Algeria,Algiers,Africa,44903225,43451666,39543154,35856344,30774621,25518074,18739378,13795915,2381741,18.8531,1.0164,0.56
9,NaN,NaN,NaN,213,ASM,American Samoa,Pago Pago,Oceania,44273,46189,51368,54849,58230,47818,32886,27075,199,222.4774,0.9831,0
10,NaN,NaN,NaN,203,AND,Andorra,Andorra la Vella,Europe,79824,77700,71746,71519,66097,53569,35611,19860,468,170.5641,1.01,0
11,NaN,NaN,NaN,42,AGO,Angola,Luanda,Africa,35588987,33428485,28127721,23364185,16394062,11828638,8330047,6029700,1246700,28.5466,1.0315,0.45

In [18]:
df4 = pd.read_excel(r"D:\Pandas\Pandas_Course\world_population3.xlsx", skiprows =6)
df4.head(12)

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Rank,CCA3,Country,Capital,Continent,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (kmÂ²),Density (per kmÂ²),Growth Rate,World Population Percentage
0,NaN,NaN,NaN,36,AFG,Afghanistan,Kabul,Asia,41128771,38972230,33753499,28189672,19542982,10694796,12486631,10752971,652230,63.0587,1.0257,0.52
1,NaN,NaN,NaN,138,ALB,Albania,Tirana,Europe,2842321,2866849,2882481,2913399,3182021,3295066,2941651,2324731,28748,98.8702,0.9957,0.04
2,NaN,NaN,NaN,34,DZA,Algeria,Algiers,Africa,44903225,43451666,39543154,35856344,30774621,25518074,18739378,13795915,2381741,18.8531,1.0164,0.56
3,NaN,NaN,NaN,213,ASM,American Samoa,Pago Pago,Oceania,44273,46189,51368,54849,58230,47818,32886,27075,199,222.4774,0.9831,0.00
4,NaN,NaN,NaN,203,AND,Andorra,Andorra la Vella,Europe,79824,77700,71746,71519,66097,53569,35611,19860,468,170.5641,1.0100,0.00
5,NaN,NaN,NaN,42,AGO,Angola,Luanda,Africa,35588987,33428485,28127721,23364185,16394062,11828638,8330047,6029700,1246700,28.5466,1.0315,0.45
6,NaN,NaN,NaN,224,AIA,Anguilla,The Valley,North America,15857,15585,14525,13172,11047,8316,6560,6283,91,174.2527,1.0066,0.00
7,NaN,NaN,NaN,201,ATG,Antigua and Barbuda,Saint Johnâ€™s,North America,93763,92664,89941,85695,75055,63328,64888,64516,442,212.1335,1.0058,0.00
8,NaN,NaN,NaN,33,ARG,Argentina,Buenos Aires,South America,45510318,45036032,43257065,41100123,37070774,32637657,28024803,23842803,2780400,16.3683,1.0052,0.57
9,NaN,NaN,NaN,140,ARM,Armenia,Yerevan,Asia,2780469,2805608,2878595,2946293,3168523,3556539,3135123,2534377,29743,93.4831,0.9962,0.03
10,NaN,NaN,NaN,198,ABW,Aruba,Oranjestad,North America,106445,106585,104257,100341,89101,65712,62267,59106,180,591.3611,0.9991,0.00
11,NaN,NaN,NaN,55,AUS,Australia,Canberra,Oceania,26177413,25670051,23820236,22019168,19017963,17048003,14706322,12595034,7692024,3.4032,1.0099,0.33

<div dir="rtl" style="text-align: right;">
4.4. التعامل مع الصفوف الفارغة في اليسار- الطريقة الأولى
  </div>

In [19]:
df4 = pd.read_excel(r"D:\Pandas\Pandas_Course\world_population3.xlsx", skiprows =6, usecols='D:T')
df4.head(12)

,Rank,CCA3,Country,Capital,Continent,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (kmÂ²),Density (per kmÂ²),Growth Rate,World Population Percentage
0,36,AFG,Afghanistan,Kabul,Asia,41128771,38972230,33753499,28189672,19542982,10694796,12486631,10752971,652230,63.0587,1.0257,0.52
1,138,ALB,Albania,Tirana,Europe,2842321,2866849,2882481,2913399,3182021,3295066,2941651,2324731,28748,98.8702,0.9957,0.04
2,34,DZA,Algeria,Algiers,Africa,44903225,43451666,39543154,35856344,30774621,25518074,18739378,13795915,2381741,18.8531,1.0164,0.56
3,213,ASM,American Samoa,Pago Pago,Oceania,44273,46189,51368,54849,58230,47818,32886,27075,199,222.4774,0.9831,0.00
4,203,AND,Andorra,Andorra la Vella,Europe,79824,77700,71746,71519,66097,53569,35611,19860,468,170.5641,1.0100,0.00
5,42,AGO,Angola,Luanda,Africa,35588987,33428485,28127721,23364185,16394062,11828638,8330047,6029700,1246700,28.5466,1.0315,0.45
6,224,AIA,Anguilla,The Valley,North America,15857,15585,14525,13172,11047,8316,6560,6283,91,174.2527,1.0066,0.00
7,201,ATG,Antigua and Barbuda,Saint Johnâ€™s,North America,93763,92664,89941,85695,75055,63328,64888,64516,442,212.1335,1.0058,0.00
8,33,ARG,Argentina,Buenos Aires,South America,45510318,45036032,43257065,41100123,37070774,32637657,28024803,23842803,2780400,16.3683,1.0052,0.57
9,140,ARM,Armenia,Yerevan,Asia,2780469,2805608,2878595,2946293,3168523,3556539,3135123,2534377,29743,93.4831,0.9962,0.03
10,198,ABW,Aruba,Oranjestad,North America,106445,106585,104257,100341,89101,65712,62267,59106,180,591.3611,0.9991,0.00
11,55,AUS,Australia,Canberra,Oceania,26177413,25670051,23820236,22019168,19017963,17048003,14706322,12595034,7692024,3.4032,1.0099,0.33


<div dir="rtl" style="text-align: right;">
4.4. التعامل مع الصفوف الفارغة في اليسار- الطريقة الثانية
  </div>

In [20]:
df5 = pd.read_excel(r"D:\Pandas\Pandas_Course\world_population3.xlsx", skiprows=6)
df5 = df5.dropna(axis=1, how = 'all')
df5.head(10)

,Rank,CCA3,Country,Capital,Continent,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (kmÂ²),Density (per kmÂ²),Growth Rate,World Population Percentage
0,36,AFG,Afghanistan,Kabul,Asia,41128771,38972230,33753499,28189672,19542982,10694796,12486631,10752971,652230,63.0587,1.0257,0.52
1,138,ALB,Albania,Tirana,Europe,2842321,2866849,2882481,2913399,3182021,3295066,2941651,2324731,28748,98.8702,0.9957,0.04
2,34,DZA,Algeria,Algiers,Africa,44903225,43451666,39543154,35856344,30774621,25518074,18739378,13795915,2381741,18.8531,1.0164,0.56
3,213,ASM,American Samoa,Pago Pago,Oceania,44273,46189,51368,54849,58230,47818,32886,27075,199,222.4774,0.9831,0.00
4,203,AND,Andorra,Andorra la Vella,Europe,79824,77700,71746,71519,66097,53569,35611,19860,468,170.5641,1.0100,0.00
5,42,AGO,Angola,Luanda,Africa,35588987,33428485,28127721,23364185,16394062,11828638,8330047,6029700,1246700,28.5466,1.0315,0.45
6,224,AIA,Anguilla,The Valley,North America,15857,15585,14525,13172,11047,8316,6560,6283,91,174.2527,1.0066,0.00
7,201,ATG,Antigua and Barbuda,Saint Johnâ€™s,North America,93763,92664,89941,85695,75055,63328,64888,64516,442,212.1335,1.0058,0.00
8,33,ARG,Argentina,Buenos Aires,South America,45510318,45036032,43257065,41100123,37070774,32637657,28024803,23842803,2780400,16.3683,1.0052,0.57
9,140,ARM,Armenia,Yerevan,Asia,2780469,2805608,2878595,2946293,3168523,3556539,3135123,2534377,29743,93.4831,0.9962,0.03

<div dir="rtl" style="text-align: right;">
5- قراءة ملفات SQL 
 </div>

In [23]:
import sqlite3

db_path = r"D:\Pandas\Pandas_Course\Chinook_Sqlite.sqlite"
conn = sqlite3.connect(db_path)
tables = pd.read_sql("SELECT name FROM sqlite_master WHERE type = 'table';", conn)
print(tables)

df_sql_cusstomer = pd.read_sql("SELECT * FROM Customer", conn)
print(df_sql_cusstomer)

             name
0           Album
1          Artist
2        Customer
3        Employee
4           Genre
5         Invoice
6     InvoiceLine
7       MediaType
8        Playlist
9   PlaylistTrack
10          Track
    CustomerId  FirstName      LastName  \
0            1       Luís     Gonçalves
1            2     Leonie        Köhler
2            3   François      Tremblay
3            4      Bjørn        Hansen
4            5  František   Wichterlová
5            6     Helena          Holý
6            7     Astrid        Gruber
7            8       Daan       Peeters
8            9       Kara       Nielsen
9           10    Eduardo       Martins
10          11  Alexandre         Rocha
11          12    Roberto       Almeida
12          13   Fernanda         Ramos
13          14       Mark       Philips
14          15   Jennifer      Peterson
15          16      Frank        Harris
16          17       Jack         Smith
17          18   Michelle        Brooks
18          19        Tim         Goyer
19          20        Dan        Miller
20          21      Kathy         Chase
21          22    Heather       Leacock
22          23       John        Gordon
23          24      Frank       Ralston
24          25     Victor       Stevens
25          26    Richard    Cunningham
26          27    Patrick          Gray
27          28      Julia       Barnett
28          29     Robert         Brown
29          30     Edward       Francis
30          31     Martha          Silk
31          32      Aaron      Mitchell
32          33      Ellie      Sullivan
33          34       João     Fernandes
34          35   Madalena       Sampaio
35          36     Hannah     Schneider
36          37       Fynn    Zimmermann
37          38     Niklas      Schröder
38          39    Camille       Bernard
39          40  Dominique      Lefebvre
40          41       Marc        Dubois
41          42      Wyatt        Girard
42          43   Isabelle       Mercier
43          44      Terhi    Hämäläinen
44          45   Ladislav        Kovács
45          46       Hugh      O'Reilly
46          47      Lucas       Mancini
47          48   Johannes  Van der Berg
48          49  Stanisław        Wójcik
49          50    Enrique         Muñoz
50          51     Joakim     Johansson
51          52       Emma         Jones
52          53       Phil        Hughes
53          54      Steve        Murray
54          55       Mark        Taylor
55          56      Diego     Gutiérrez
56          57       Luis         Rojas
57          58      Manoj        Pareek
58          59       Puja    Srivastava

                                             Company  \
0   Embraer - Empresa Brasileira de Aeronáutica S.A.
1                                               None
2                                               None
3                                               None
4                                   JetBrains s.r.o.
5                                               None
6                                               None
7                                               None
8                                               None
9                                   Woodstock Discos
10                              Banco do Brasil S.A.
11                                            Riotur
12                                              None
13                                             Telus
14                                     Rogers Canada
15                                       Google Inc.
16                             Microsoft Corporation
17                                              None
18                                        Apple Inc.
19                                              None
20                                              None
21                                              None
22                                              None
23                                              None
24                                              None
25                                              None
26                                              None
27                                              None
28                                              None
29                                              None
30                                              None
31                                              None
32                                              None
33                                              None
34                                              None
35                                              None
36                                              None
37                                              None
38                                              None
39                                              None
40                                              None
41                                              None
42                                              None
43                                              None
44                                              None
45                                              None
46                                              None
47                                              None
48                                              None
49                                              None
50                                              None
51                                              None
52                                              None
53                                              None
54                                              None
55                                              None
56                                              None
57                                              None
58                                              None

                                     Address                 City   State  \
0            Av. Brigadeiro Faria Lima, 2170  São José dos Campos      SP
1                    Theodor-Heuss-Straße 34            Stuttgart    None
2                          1498 rue Bélanger             Montréal      QC
3                           Ullevålsveien 14                 Oslo    None
4                              Klanova 9/506               Prague    None
5                              Rilská 3174/6               Prague    None
6       Rotenturmstraße 4, 1010 Innere Stadt               Vienne    None
7                            Grétrystraat 63             Brussels    None
8                        Sønder Boulevard 51           Copenhagen    None
9                  Rua Dr. Falcão Filho, 155            São Paulo      SP
10                        Av. Paulista, 2022            São Paulo      SP
11                          Praça Pio X, 119       Rio de Janeiro      RJ
12                              Qe 7 Bloco G             Brasília      DF
13                            8210 111 ST NW             Edmonton      AB
14                       700 W Pender Street            Vancouver      BC
15                 1600 Amphitheatre Parkway        Mountain View      CA
16                           1 Microsoft Way              Redmond      WA
17                              627 Broadway             New York      NY
18                           1 Infinite Loop            Cupertino      CA
19                      541 Del Medio Avenue        Mountain View      CA
20                          801 W 4th Street                 Reno      NV
21                          120 S Orange Ave              Orlando      FL
22                           69 Salem Street               Boston      MA
23                     162 E Superior Street              Chicago      IL
24                     319 N. Frances Street              Madison      WI
25                       2211 W Berry Street           Fort Worth      TX
26                           1033 N Park Ave               Tucson      AZ
27                               302 S 700 E       Salt Lake City      UT
28                    796 Dundas Street West              Toronto      ON
29                          230 Elgin Street               Ottawa      ON
30                     194A Chain Lake Drive              Halifax      NS
31                        696 Osborne Street             Winnipeg      MB
32                            5112 48 Street          Yellowknife      NT
33                        Rua da Assunção 53               Lisbon    None
34  Rua dos Campeões Europeus de Viena, 4350                Porto    None
35                        Tauentzienstraße 8               Berlin    None
36                          Berger Straße 10            Frankfurt    None
37                       Barbarossastraße 19               Berlin    None
38                             4, Rue Milton                Paris    None
39                            8, Rue Hanovre                Paris    None
40                       11, Place Bellecour                 Lyon    None
41                    9, Place Louis Barthou             Bordeaux    None
42                          68, Rue Jouvence                Dijon    None
43                           Porthaninkatu 9             Helsinki    None
44                         Erzsébet krt. 58.             Budapest    None
45                          3 Chatham Street               Dublin  Dublin
46                    Via Degli Scipioni, 43                 Rome      RM
47                     Lijnbaansgracht 120bg            Amsterdam      VV
48                              Ordynacka 10               Warsaw    None
49                        C/ San Bernardo 85               Madrid    None
50                               Celsiusg. 9            Stockholm    None
51                         202 Hoxton Street               London    None
52                              113 Lupus St               London    None
53                            110 Raeburn Pl           Edinburgh     None
54                         421 Bourke Street               Sidney     NSW
55                        307 Macacha Güemes         Buenos Aires    None
56                           Calle Lira, 198             Santiago    None
57                       12,Community Centre                Delhi    None
58                         3,Raj Bhavan Road            Bangalore    None

           Country  PostalCode                Phone                 Fax  \
0           Brazil   12227-000   +55 (12) 3923-5555  +55 (12) 3923-5566
1          Germany       70174     +49 0711 2842222                None
2           Canada     H2G 1A7    +1 (514) 721-4711                None
3           Norway        0171      +47 22 44 22 22                None
4   Czech Republic       14700     +420 2 4172 5555    +420 2 4172 5555
5   Czech Republic       14300     +420 2 4177 0449                None
6          Austria        1010       +43 01 5134505                None
7          Belgium        1000     +32 02 219 03 03                None
8          Denmark        1720       +453 3331 9991                None
9           Brazil   01007-010   +55 (11) 3033-5446  +55 (11) 3033-4564
10          Brazil   01310-200   +55 (11) 3055-3278  +55 (11) 3055-8131
11          Brazil   20040-020   +55 (21) 2271-7000  +55 (21) 2271-7070
12          Brazil   71020-677   +55 (61) 3363-5547  +55 (61) 3363-7855
13          Canada     T6G 2C7    +1 (780) 434-4554   +1 (780) 434-5565
14          Canada     V6C 1G8    +1 (604) 688-2255   +1 (604) 688-8756
15             USA  94043-1351    +1 (650) 253-0000   +1 (650) 253-0000
16             USA  98052-8300    +1 (425) 882-8080   +1 (425) 882-8081
17             USA  10012-2612    +1 (212) 221-3546   +1 (212) 221-4679
18             USA       95014    +1 (408) 996-1010   +1 (408) 996-1011
19             USA   94040-111    +1 (650) 644-3358                None
20             USA       89503    +1 (775) 223-7665                None
21             USA       32801    +1 (407) 999-7788                None
22             USA        2113    +1 (617) 522-1333                None
23             USA       60611    +1 (312) 332-3232                None
24             USA       53703    +1 (608) 257-0597                None
25             USA       76110    +1 (817) 924-7272                None
26             USA       85719    +1 (520) 622-4200                None
27             USA       84102    +1 (801) 531-7272                None
28          Canada     M6J 1V1    +1 (416) 363-8888                None
29          Canada     K2P 1L7    +1 (613) 234-3322                None
30          Canada     B3S 1C5    +1 (902) 450-0450                None
31          Canada     R3L 2B9    +1 (204) 452-6452                None
32          Canada     X1A 1N6    +1 (867) 920-2233                None
33        Portugal        None   +351 (213) 466-111                None
34        Portugal        None   +351 (225) 022-448                None
35         Germany       10789     +49 030 26550280                None
36         Germany       60316     +49 069 40598889                None
37         Germany       10779      +49 030 2141444                None
38          France       75009   +33 01 49 70 65 65                None
39          France       75002   +33 01 47 42 71 71                None
40          France       69002   +33 04 78 30 30 30                None
41          France       33000   +33 05 56 96 96 96                None
42          France       21000   +33 03 80 73 66 99                None
43         Finland       00530     +358 09 870 2000                None
44         Hungary      H-1073                 None                None
45         Ireland        None      +353 01 6792424                None
46           Italy       00192      +39 06 39733434                None
47     Netherlands        1016      +31 020 6223130                None
48          Poland      00-358     +48 22 828 37 39                None
49           Spain       28015      +34 914 454 454                None
50          Sweden       11230     +46 08-651 52 52                None
51  United Kingdom      N1 5LH    +44 020 7707 0707                None
52  United Kingdom    SW1V 3EN    +44 020 7976 5722                None
53  United Kingdom     EH4 1HH    +44 0131 315 3300                None
54       Australia        2010   +61 (02) 9332 3633                None
55       Argentina        1106  +54 (0)11 4311 4333                None
56           Chile        None    +56 (0)2 635 4444                None
57           India      110017    +91 0124 39883988                None
58           India      560001     +91 080 22289999                None

                            Email  SupportRepId
0            luisg@embraer.com.br             3
1           leonekohler@surfeu.de             5
2             ftremblay@gmail.com             3
3           bjorn.hansen@yahoo.no             4
4        frantisekw@jetbrains.com             4
5                 hholy@gmail.com             5
6          astrid.gruber@apple.at             5
7           daan_peeters@apple.be             4
8           kara.nielsen@jubii.dk             4
9        eduardo@woodstock.com.br             4
10               alero@uol.com.br             5
11  roberto.almeida@riotur.gov.br             3
12       fernadaramos4@uol.com.br             4
13             mphilips12@shaw.ca             5
14            jenniferp@rogers.ca             3
15             fharris@google.com             4
16        jacksmith@microsoft.com             5
17              michelleb@aol.com             3
18               tgoyer@apple.com             3
19            dmiller@comcast.com             4
20            kachase@hotmail.com             5
21             hleacock@gmail.com             4
22         johngordon22@yahoo.com             4
23             fralston@gmail.com             3
24             vstevens@yahoo.com             5
25       ricunningham@hotmail.com             4
26           patrick.gray@aol.com             4
27            jubarnett@gmail.com             5
28               robbrown@shaw.ca             3
29            edfrancis@yachoo.ca             3
30           marthasilk@gmail.com             5
31         aaronmitchell@yahoo.ca             4
32         ellie.sullivan@shaw.ca             3
33            jfernandes@yahoo.pt             4
34              masampaio@sapo.pt             4
35      hannah.schneider@yahoo.de             5
36           fzimmermann@yahoo.de             3
37            nschroder@surfeu.de             3
38       camille.bernard@yahoo.fr             4
39    dominiquelefebvre@gmail.com             4
40        marc.dubois@hotmail.com             5
41          wyatt.girard@yahoo.fr             3
42      isabelle_mercier@apple.fr             3
43      terhi.hamalainen@apple.fi             3
44       ladislav_kovacs@apple.hu             3
45           hughoreilly@apple.ie             3
46         lucas.mancini@yahoo.it             5
47        johavanderberg@yahoo.nl             5
48         stanisław.wójcik@wp.pl             4
49         enrique_munoz@yahoo.es             5
50      joakim.johansson@yahoo.se             5
51         emma_jones@hotmail.com             3
52          phil.hughes@gmail.com             3
53          steve.murray@yahoo.uk             5
54           mark.taylor@yahoo.au             4
55       diego.gutierrez@yahoo.ar             4
56             luisrojas@yahoo.cl             5
57        manoj.pareek@rediff.com             3
58       puja_srivastava@yahoo.in             3

<div dir="rtl" style="text-align: right;">
6- قراءة البيانات من Clipboard 
 </div>

In [24]:
df_clip = pd.read_clipboard()
print(df_clip)

    CustomerId  FirstName   LastName            \
0            0          1       Luís    Gonçalves
1            1          2     Leonie       Köhler
2            2          3   François     Tremblay
3            3          4      Bjørn       Hansen
4            4          5  František  Wichterlová
5            5          6     Helena         Holý
6            6          7     Astrid       Gruber
7            7          8       Daan      Peeters
8            8          9       Kara      Nielsen
9            9         10    Eduardo      Martins
10          10         11  Alexandre        Rocha
11          11         12    Roberto      Almeida

<div dir="rtl" style="text-align: right;">
7- قراءة جداول HTML مباشرة من الويب
 </div>

In [ ]:
# pip install requests

In [26]:
import requests
from io import StringIO
url = "https://en.wikipedia.org/wiki/List_of_countries_and_dependencies_by_population"

headers = {"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64)"}

response = requests.get(url, headers= headers)
html = response.text

dfs = pd.read_html(StringIO(html))

print("Tables Number", len(dfs))

Tables Number 3

In [33]:
df_population = dfs[0]
df_population.head(20)

,Location,Population,% of world,Date,Source (official or from the United Nations),Notes
0,World,8232000000,100%,13 Jun 2025,UN projection[1][3],NaN
1,India,1417492000,17.2%,1 Jul 2025,Official projection[4],[b]
2,China,1404890000,17.0%,31 Dec 2025,Official estimate[5],[c]
3,United States,341784857,4.1%,1 Jul 2025,Official estimate[6],[d]
4,Indonesia,288315089,3.5%,31 Dec 2025,National annual projection[7],NaN
5,Pakistan,241499431,2.9%,1 Mar 2023,2023 census result[8],[e]
6,Nigeria,223800000,2.7%,1 Jul 2023,Official projection[9],NaN
7,Brazil,213421037,2.6%,1 Jul 2025,Official estimate[10],NaN
8,Bangladesh,169828911,2.1%,14 Jun 2022,2022 census result[11],[f]
9,Russia,146028325,1.8%,1 Jan 2025,Official estimate[13],[g]
10,Mexico,131001723,1.6%,31 Dec 2025,National quarterly estimate[14],NaN
11,Japan,122850000,1.5%,1 Mar 2026,Monthly national estimate[15],NaN
12,Philippines,114123600,1.4%,1 Jul 2025,Official projection[16],NaN
13,Democratic Republic of the Congo,112832000,1.4%,1 Jul 2025,UN projection[17],NaN
14,Ethiopia,111652998,1.4%,1 Jul 2025,National annual projection[18],NaN
15,Egypt,107868296,1.3%,1 Jul 2025,Official estimate[19],NaN
16,Vietnam,102300000,1.2%,31 Dec 2025,Official estimate[20],NaN
17,Iran,86563000,1.1%,20 Mar 2025,Official projection[21],NaN
18,Turkey,86092168,1.0%,31 Dec 2025,Official estimate[22],NaN
19,Germany,83497147,1.0%,30 Sep 2025,National quarterly estimate[23],NaN

<div dir="rtl" style="text-align: right;">
8. استكشاف البيانات


 </div>

<div dir="rtl" style="text-align: right;">
8.1 معرفة اسماء الاعمدة

 </div>

In [34]:
df5.columns

Index(['Rank', 'CCA3', 'Country', 'Capital', 'Continent', '2022 Population',
       '2020 Population', '2015 Population', '2010 Population',
       '2000 Population', '1990 Population', '1980 Population',
       '1970 Population', 'Area (kmÂ²)', 'Density (per kmÂ²)', 'Growth Rate',
       'World Population Percentage'],
      dtype='object')




 <div dir="rtl" style="text-align: right;">
8.2 معرفة حجم البيانات عدد الصفوف والأعمدة

 </div>

In [35]:
df5.shape

(234, 17)

<div dir="rtl" style="text-align: right;">
8.3 عرض معلومات هيكلية عن البيانات


 </div>

In [36]:
df5.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 234 entries, 0 to 233
Data columns (total 17 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Rank                         234 non-null    int64
 1   CCA3                         234 non-null    object
 2   Country                      234 non-null    object
 3   Capital                      234 non-null    object
 4   Continent                    234 non-null    object
 5   2022 Population              234 non-null    int64
 6   2020 Population              234 non-null    int64
 7   2015 Population              234 non-null    int64
 8   2010 Population              234 non-null    int64
 9   2000 Population              234 non-null    int64
 10  1990 Population              234 non-null    int64
 11  1980 Population              234 non-null    int64
 12  1970 Population              234 non-null    int64
 13  Area (kmÂ²)                  234 non-null    int64
 14  Density (per kmÂ²)           234 non-null    float64
 15  Growth Rate                  234 non-null    float64
 16  World Population Percentage  234 non-null    float64
dtypes: float64(3), int64(10), object(4)
memory usage: 31.2+ KB

<div dir="rtl" style="text-align: right;">

8.4 معرفة نوع البيانات لكل عمود 

</div>

In [37]:
df5.dtypes

Rank                             int64
CCA3                            object
Country                         object
Capital                         object
Continent                       object
2022 Population                  int64
2020 Population                  int64
2015 Population                  int64
2010 Population                  int64
2000 Population                  int64
1990 Population                  int64
1980 Population                  int64
1970 Population                  int64
Area (kmÂ²)                      int64
Density (per kmÂ²)             float64
Growth Rate                    float64
World Population Percentage    float64
dtype: object

<div dir="rtl" style="text-align: right;">

8.5 الإحصائيات الوصفية للأعمدة الرقمية

 </div>

In [38]:
df5.describe()

,Rank,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (kmÂ²),Density (per kmÂ²),Growth Rate,World Population Percentage
count,234.000000,2.340000e+02,2.340000e+02,2.340000e+02,2.340000e+02,2.340000e+02,2.340000e+02,2.340000e+02,2.340000e+02,2.340000e+02,234.000000,234.000000,234.000000
mean,117.500000,3.407441e+07,3.350107e+07,3.172996e+07,2.984524e+07,2.626947e+07,2.271022e+07,1.898462e+07,1.578691e+07,5.814494e+05,452.127044,1.009577,0.427051
std,67.694165,1.367664e+08,1.355899e+08,1.304050e+08,1.242185e+08,1.116982e+08,9.783217e+07,8.178519e+07,6.779509e+07,1.761841e+06,2066.121904,0.013385,1.714977
min,1.000000,5.100000e+02,5.200000e+02,5.640000e+02,5.960000e+02,6.510000e+02,7.000000e+02,7.330000e+02,7.520000e+02,1.000000e+00,0.026100,0.912000,0.000000
25%,59.250000,4.197385e+05,4.152845e+05,4.046760e+05,3.931490e+05,3.272420e+05,2.641158e+05,2.296142e+05,1.559970e+05,2.650000e+03,38.417875,1.001775,0.010000
50%,117.500000,5.559944e+06,5.493074e+06,5.307400e+06,4.942770e+06,4.292907e+06,3.825410e+06,3.141146e+06,2.604830e+06,8.119950e+04,95.346750,1.007900,0.070000
75%,175.750000,2.247650e+07,2.144798e+07,1.973085e+07,1.915957e+07,1.576230e+07,1.186923e+07,9.826054e+06,8.817329e+06,4.304258e+05,238.933250,1.016950,0.280000
max,234.000000,1.425887e+09,1.424930e+09,1.393715e+09,1.348191e+09,1.264099e+09,1.153704e+09,9.823725e+08,8.225344e+08,1.709824e+07,23172.266700,1.069100,17.880000

<div dir="rtl" style="text-align: right;">

8.6 معاينة أول عدة صفوف من البيانات

 </div>

In [39]:
df5.head()

,Rank,CCA3,Country,Capital,Continent,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (kmÂ²),Density (per kmÂ²),Growth Rate,World Population Percentage
0,36,AFG,Afghanistan,Kabul,Asia,41128771,38972230,33753499,28189672,19542982,10694796,12486631,10752971,652230,63.0587,1.0257,0.52
1,138,ALB,Albania,Tirana,Europe,2842321,2866849,2882481,2913399,3182021,3295066,2941651,2324731,28748,98.8702,0.9957,0.04
2,34,DZA,Algeria,Algiers,Africa,44903225,43451666,39543154,35856344,30774621,25518074,18739378,13795915,2381741,18.8531,1.0164,0.56
3,213,ASM,American Samoa,Pago Pago,Oceania,44273,46189,51368,54849,58230,47818,32886,27075,199,222.4774,0.9831,0.00
4,203,AND,Andorra,Andorra la Vella,Europe,79824,77700,71746,71519,66097,53569,35611,19860,468,170.5641,1.0100,0.00

<div dir="rtl" style="text-align: right;">
8.7 معاينة آخر عدد من الصفوف

 </div>

In [40]:
df5.tail()

,Rank,CCA3,Country,Capital,Continent,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (kmÂ²),Density (per kmÂ²),Growth Rate,World Population Percentage
229,226,WLF,Wallis and Futuna,Mata-Utu,Oceania,11572,11655,12182,13142,14723,13454,11315,9377,142,81.4930,0.9953,0.00
230,172,ESH,Western Sahara,El AaiÃºn,Africa,575986,556048,491824,413296,270375,178529,116775,76371,266000,2.1654,1.0184,0.01
231,46,YEM,Yemen,Sanaa,Asia,33696614,32284046,28516545,24743946,18628700,13375121,9204938,6843607,527968,63.8232,1.0217,0.42
232,63,ZMB,Zambia,Lusaka,Africa,20017675,18927715,16248230,13792086,9891136,7686401,5720438,4281671,752612,26.5976,1.0280,0.25
233,74,ZWE,Zimbabwe,Harare,Africa,16320537,15669666,14154937,12839771,11834676,10113893,7049926,5202918,390757,41.7665,1.0204,0.20

<div dir="rtl" style="text-align: right;">
8.8 أخذ عينة عشوائية من البيانات

 </div>

In [41]:
df5.sample(20)

,Rank,CCA3,Country,Capital,Continent,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (kmÂ²),Density (per kmÂ²),Growth Rate,World Population Percentage
44,223,COK,Cook Islands,Avarua,Oceania,17011,17029,17695,17212,15897,17123,17651,20470,236,72.0805,1.0005,0.00
110,103,LAO,Laos,Vientiane,Asia,7529475,7319399,6787419,6323418,5430853,4314443,3297519,2675283,236800,31.7968,1.0141,0.09
12,99,AUT,Austria,Vienna,Europe,8939617,8907777,8642421,8362829,8010428,7678729,7547561,7465301,83871,106.5877,1.0020,0.11
26,144,BWA,Botswana,Gaborone,Africa,2630296,2546402,2305171,2091664,1726985,1341474,938578,592244,582000,4.5194,1.0162,0.03
194,29,KOR,South Korea,Seoul,Asia,51815810,51844690,50994401,48813042,46788591,44120039,38170501,32601143,100210,517.0722,0.9997,0.65
62,159,SWZ,Eswatini,Mbabane,Africa,1201670,1180655,1133936,1099920,1030496,854011,598564,442865,17364,69.2047,1.0079,0.02
40,65,CHL,Chile,Santiago,South America,19603733,19300315,17870124,17004162,15351799,13342868,11469828,9820481,756102,25.9274,1.0057,0.25
69,184,GUF,French Guiana,Cayenne,South America,304557,290969,257026,228453,164351,113931,66825,46484,83534,3.6459,1.0239,0.00
73,131,GEO,Georgia,Tbilisi,Asia,3744385,3765912,3771132,3836831,4265172,5391636,5145843,4800426,69700,53.7214,0.9964,0.05
180,218,SMR,San Marino,San Marino,Europe,33660,34007,33570,31608,26823,23132,21346,18169,61,551.8033,0.9975,0.00
43,163,COM,Comoros,Moroni,Africa,836774,806166,730216,656024,536758,431119,328328,242351,1862,449.3953,1.0184,0.01
30,108,BGR,Bulgaria,Sofia,Europe,6781953,6979175,7309253,7592273,8097691,8767778,8980606,8582950,110879,61.1654,0.9849,0.09
124,59,MLI,Mali,Bamako,Africa,22593590,21224040,18112907,15529181,11239101,8945026,7372581,6153587,1240192,18.2178,1.0314,0.28
143,49,NPL,Nepal,Kathmandu,Asia,30547580,29348627,27610325,27161567,24559500,19616530,15600442,12501285,147181,207.5511,1.0171,0.38
120,50,MDG,Madagascar,Antananarivo,Africa,29611714,28225177,24850912,21731053,16216431,11882762,8948162,6639751,587041,50.4423,1.0241,0.37
85,149,GNB,Guinea-Bissau,Bissau,Africa,2105566,2015828,1788919,1567220,1230849,973551,831462,591663,36125,58.2856,1.0218,0.03
233,74,ZWE,Zimbabwe,Harare,Africa,16320537,15669666,14154937,12839771,11834676,10113893,7049926,5202918,390757,41.7665,1.0204,0.20
41,1,CHN,China,Beijing,Asia,1425887337,1424929781,1393715448,1348191368,1264099069,1153704252,982372466,822534450,9706961,146.8933,1.0000,17.88
121,62,MWI,Malawi,Lilongwe,Africa,20405317,19377061,16938942,14718422,11229387,9539665,6267369,4625141,118484,172.2200,1.0259,0.26
45,124,CRI,Costa Rica,San JosÃ©,North America,5180829,5123105,4895242,4622252,3979193,3158253,2414303,1855697,51100,101.3861,1.0052,0.06

<div dir="rtl" style="text-align: right;">

8.9 معاينة  قيم عمود محدد

 </div>

In [42]:
df5['Rank']

0       36
1      138
2       34
3      213
4      203
      ...
229    226
230    172
231     46
232     63
233     74
Name: Rank, Length: 234, dtype: int64

<div dir="rtl" style="text-align: right;">

8.10 الكشف عن القيم الفارغة
 </div>

In [43]:
df5.isnull()

,Rank,CCA3,Country,Capital,Continent,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (kmÂ²),Density (per kmÂ²),Growth Rate,World Population Percentage
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
229,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
230,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
231,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
232,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
233,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

<div dir="rtl" style="text-align: right;">

8.11 الكشف عن عدد القيم الفارغة ضمن كل عمود 

</div>

In [44]:
df5.isnull().sum()

Rank                           0
CCA3                           0
Country                        0
Capital                        0
Continent                      0
2022 Population                0
2020 Population                0
2015 Population                0
2010 Population                0
2000 Population                0
1990 Population                0
1980 Population                0
1970 Population                0
Area (kmÂ²)                    0
Density (per kmÂ²)             0
Growth Rate                    0
World Population Percentage    0
dtype: int64

<div dir="rtl" style="text-align: right;">

8.12 القيم الفريدة لكل عمود

</div>

In [45]:
df5.nunique()

Rank                           234
CCA3                           234
Country                        234
Capital                        234
Continent                        6
2022 Population                234
2020 Population                234
2015 Population                234
2010 Population                234
2000 Population                234
1990 Population                234
1980 Population                234
1970 Population                234
Area (kmÂ²)                    233
Density (per kmÂ²)             234
Growth Rate                    180
World Population Percentage     70
dtype: int64