

<div dir="rtl" style="text-align: right;">

## Pandas Course الدرس الثاني 2
 </div>


<div dir="rtl" style="text-align: right;">

## Indexing الفهرسة

 </div>



<div dir="rtl" style="text-align: right;">
0. استيراد المكتبة


 </div>

In [1]:
import pandas as pd


<div dir="rtl" style="text-align: right;">
1. قراءة الملف 

 </div>

In [3]:
df = pd.read_csv(r"D:\Pandas\Pandas_Course\world_population.csv")
df.head()

,Rank,CCA3,Country,Capital,Continent,Average,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (km²),Density (per km²),Growth Rate,World Population Percentage
0,36,AFG,Afghanistan,Kabul,Asia,2.444019e+07,41128771.0,38972230.0,33753499.0,28189672.0,19542982.0,10694796.0,12486631.0,10752971.0,652230.0,63.0587,1.0257,0.52
1,138,ALB,Albania,Tirana,Europe,2.906065e+06,2842321.0,2866849.0,2882481.0,2913399.0,3182021.0,3295066.0,2941651.0,2324731.0,28748.0,98.8702,0.9957,0.04
2,34,DZA,Algeria,Algiers,Africa,3.157280e+07,44903225.0,43451666.0,39543154.0,35856344.0,30774621.0,25518074.0,18739378.0,13795915.0,2381741.0,18.8531,1.0164,0.56
3,213,ASM,American Samoa,Pago Pago,Oceania,4.533600e+04,44273.0,46189.0,51368.0,54849.0,58230.0,47818.0,32886.0,27075.0,199.0,222.4774,0.9831,0.00
4,203,AND,Andorra,Andorra la Vella,Europe,5.949075e+04,79824.0,77700.0,71746.0,71519.0,66097.0,53569.0,35611.0,19860.0,468.0,170.5641,1.0100,0.00



<div dir="rtl" style="text-align: right;">

2. قراءة الملف مع تحديد عمود الفهرسة مباشراً

 </div>

In [4]:
df = pd.read_csv(r"D:\Pandas\Pandas_Course\world_population.csv", index_col='Country')
df.head()

,Rank,CCA3,Capital,Continent,Average,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (km²),Density (per km²),Growth Rate,World Population Percentage
Country,,,,,,,,,,,,,,,,,
Afghanistan,36,AFG,Kabul,Asia,2.444019e+07,41128771.0,38972230.0,33753499.0,28189672.0,19542982.0,10694796.0,12486631.0,10752971.0,652230.0,63.0587,1.0257,0.52
Albania,138,ALB,Tirana,Europe,2.906065e+06,2842321.0,2866849.0,2882481.0,2913399.0,3182021.0,3295066.0,2941651.0,2324731.0,28748.0,98.8702,0.9957,0.04
Algeria,34,DZA,Algiers,Africa,3.157280e+07,44903225.0,43451666.0,39543154.0,35856344.0,30774621.0,25518074.0,18739378.0,13795915.0,2381741.0,18.8531,1.0164,0.56
American Samoa,213,ASM,Pago Pago,Oceania,4.533600e+04,44273.0,46189.0,51368.0,54849.0,58230.0,47818.0,32886.0,27075.0,199.0,222.4774,0.9831,0.00
Andorra,203,AND,Andorra la Vella,Europe,5.949075e+04,79824.0,77700.0,71746.0,71519.0,66097.0,53569.0,35611.0,19860.0,468.0,170.5641,1.0100,0.00

<div dir="rtl" style="text-align: right;">
إعادة الفهرس إلى العمود الإفتراضي مع الإبقاء على الفهرس القديم
 </div>

In [5]:
df.reset_index(drop=False, inplace=True)

df.head(10)

,Country,Rank,CCA3,Capital,Continent,Average,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (km²),Density (per km²),Growth Rate,World Population Percentage
0,Afghanistan,36,AFG,Kabul,Asia,2.444019e+07,41128771.0,38972230.0,33753499.0,28189672.0,19542982.0,10694796.0,12486631.0,10752971.0,652230.0,63.0587,1.0257,0.52
1,Albania,138,ALB,Tirana,Europe,2.906065e+06,2842321.0,2866849.0,2882481.0,2913399.0,3182021.0,3295066.0,2941651.0,2324731.0,28748.0,98.8702,0.9957,0.04
2,Algeria,34,DZA,Algiers,Africa,3.157280e+07,44903225.0,43451666.0,39543154.0,35856344.0,30774621.0,25518074.0,18739378.0,13795915.0,2381741.0,18.8531,1.0164,0.56
3,American Samoa,213,ASM,Pago Pago,Oceania,4.533600e+04,44273.0,46189.0,51368.0,54849.0,58230.0,47818.0,32886.0,27075.0,199.0,222.4774,0.9831,0.00
4,Andorra,203,AND,Andorra la Vella,Europe,5.949075e+04,79824.0,77700.0,71746.0,71519.0,66097.0,53569.0,35611.0,19860.0,468.0,170.5641,1.0100,0.00
5,Angola,42,AGO,Luanda,Africa,2.038648e+07,35588987.0,33428485.0,28127721.0,23364185.0,16394062.0,11828638.0,8330047.0,6029700.0,1246700.0,28.5466,1.0315,0.45
6,Anguilla,224,AIA,The Valley,North America,1.141812e+04,15857.0,15585.0,14525.0,13172.0,11047.0,8316.0,6560.0,6283.0,91.0,174.2527,1.0066,0.00
7,Antigua and Barbuda,201,ATG,Saint John’s,North America,7.873125e+04,93763.0,92664.0,89941.0,85695.0,75055.0,63328.0,64888.0,64516.0,442.0,212.1335,1.0058,0.00
8,Argentina,33,ARG,Buenos Aires,South America,3.705995e+07,45510318.0,45036032.0,43257065.0,41100123.0,37070774.0,32637657.0,28024803.0,23842803.0,2780400.0,16.3683,1.0052,0.57
9,Armenia,140,ARM,Yerevan,Asia,2.975691e+06,2780469.0,2805608.0,2878595.0,2946293.0,3168523.0,3556539.0,3135123.0,2534377.0,29743.0,93.4831,0.9962,0.03



<div dir="rtl" style="text-align: right;">
4. استخدام set_index لتغيير الفهرس الإفتراضي و تعيين فهرس جديد 

 </div>

In [6]:
df.set_index("Country", inplace=True)
df.head(10)

,Rank,CCA3,Capital,Continent,Average,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (km²),Density (per km²),Growth Rate,World Population Percentage
Country,,,,,,,,,,,,,,,,,
Afghanistan,36,AFG,Kabul,Asia,2.444019e+07,41128771.0,38972230.0,33753499.0,28189672.0,19542982.0,10694796.0,12486631.0,10752971.0,652230.0,63.0587,1.0257,0.52
Albania,138,ALB,Tirana,Europe,2.906065e+06,2842321.0,2866849.0,2882481.0,2913399.0,3182021.0,3295066.0,2941651.0,2324731.0,28748.0,98.8702,0.9957,0.04
Algeria,34,DZA,Algiers,Africa,3.157280e+07,44903225.0,43451666.0,39543154.0,35856344.0,30774621.0,25518074.0,18739378.0,13795915.0,2381741.0,18.8531,1.0164,0.56
American Samoa,213,ASM,Pago Pago,Oceania,4.533600e+04,44273.0,46189.0,51368.0,54849.0,58230.0,47818.0,32886.0,27075.0,199.0,222.4774,0.9831,0.00
Andorra,203,AND,Andorra la Vella,Europe,5.949075e+04,79824.0,77700.0,71746.0,71519.0,66097.0,53569.0,35611.0,19860.0,468.0,170.5641,1.0100,0.00
Angola,42,AGO,Luanda,Africa,2.038648e+07,35588987.0,33428485.0,28127721.0,23364185.0,16394062.0,11828638.0,8330047.0,6029700.0,1246700.0,28.5466,1.0315,0.45
Anguilla,224,AIA,The Valley,North America,1.141812e+04,15857.0,15585.0,14525.0,13172.0,11047.0,8316.0,6560.0,6283.0,91.0,174.2527,1.0066,0.00
Antigua and Barbuda,201,ATG,Saint John’s,North America,7.873125e+04,93763.0,92664.0,89941.0,85695.0,75055.0,63328.0,64888.0,64516.0,442.0,212.1335,1.0058,0.00
Argentina,33,ARG,Buenos Aires,South America,3.705995e+07,45510318.0,45036032.0,43257065.0,41100123.0,37070774.0,32637657.0,28024803.0,23842803.0,2780400.0,16.3683,1.0052,0.57
Armenia,140,ARM,Yerevan,Asia,2.975691e+06,2780469.0,2805608.0,2878595.0,2946293.0,3168523.0,3556539.0,3135123.0,2534377.0,29743.0,93.4831,0.9962,0.03

<div dir="rtl" style="text-align: right;">
إعادة الفهرس إلى العمود الإفتراضي 
 </div>

In [7]:
df.reset_index(inplace= True)
df.head()

,Country,Rank,CCA3,Capital,Continent,Average,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (km²),Density (per km²),Growth Rate,World Population Percentage
0,Afghanistan,36,AFG,Kabul,Asia,2.444019e+07,41128771.0,38972230.0,33753499.0,28189672.0,19542982.0,10694796.0,12486631.0,10752971.0,652230.0,63.0587,1.0257,0.52
1,Albania,138,ALB,Tirana,Europe,2.906065e+06,2842321.0,2866849.0,2882481.0,2913399.0,3182021.0,3295066.0,2941651.0,2324731.0,28748.0,98.8702,0.9957,0.04
2,Algeria,34,DZA,Algiers,Africa,3.157280e+07,44903225.0,43451666.0,39543154.0,35856344.0,30774621.0,25518074.0,18739378.0,13795915.0,2381741.0,18.8531,1.0164,0.56
3,American Samoa,213,ASM,Pago Pago,Oceania,4.533600e+04,44273.0,46189.0,51368.0,54849.0,58230.0,47818.0,32886.0,27075.0,199.0,222.4774,0.9831,0.00
4,Andorra,203,AND,Andorra la Vella,Europe,5.949075e+04,79824.0,77700.0,71746.0,71519.0,66097.0,53569.0,35611.0,19860.0,468.0,170.5641,1.0100,0.00

<div dir="rtl" style="text-align: right;">

4. الفهرسة المركبة: اي جعل اكثر من عمود فهرساً
 </div>

In [9]:
df.set_index(['Continent', 'Country'], inplace=True)

df.head()

,,Rank,CCA3,Capital,Average,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (km²),Density (per km²),Growth Rate,World Population Percentage
Continent,Country,,,,,,,,,,,,,,,,
Asia,Afghanistan,36,AFG,Kabul,2.444019e+07,41128771.0,38972230.0,33753499.0,28189672.0,19542982.0,10694796.0,12486631.0,10752971.0,652230.0,63.0587,1.0257,0.52
Europe,Albania,138,ALB,Tirana,2.906065e+06,2842321.0,2866849.0,2882481.0,2913399.0,3182021.0,3295066.0,2941651.0,2324731.0,28748.0,98.8702,0.9957,0.04
Africa,Algeria,34,DZA,Algiers,3.157280e+07,44903225.0,43451666.0,39543154.0,35856344.0,30774621.0,25518074.0,18739378.0,13795915.0,2381741.0,18.8531,1.0164,0.56
Oceania,American Samoa,213,ASM,Pago Pago,4.533600e+04,44273.0,46189.0,51368.0,54849.0,58230.0,47818.0,32886.0,27075.0,199.0,222.4774,0.9831,0.00
Europe,Andorra,203,AND,Andorra la Vella,5.949075e+04,79824.0,77700.0,71746.0,71519.0,66097.0,53569.0,35611.0,19860.0,468.0,170.5641,1.0100,0.00


<div dir="rtl" style="text-align: right;">
5. فرز الصفوف حسب الفهرس

 </div>

In [10]:
df.sort_index()

                            Rank CCA3      Capital       Average  \
Continent     Country
Africa        Algeria         34  DZA      Algiers  3.157280e+07
              Angola          42  AGO       Luanda  2.038648e+07
              Benin           77  BEN   Porto-Novo  8.170413e+06
              Botswana       144  BWA     Gaborone  1.771602e+06
              Burkina Faso    58  BFA  Ouagadougou  1.407377e+07
...                          ...  ...          ...           ...
South America Paraguay       109  PRY     Asunción  5.002089e+06
              Peru            44  PER         Lima  2.588926e+07
              Suriname       170  SUR   Paramaribo  4.991805e+05
              Uruguay        133  URY   Montevideo  3.220075e+06
              Venezuela       51  VEN      Caracas  2.319334e+07

                            2022 Population  2020 Population  2015 Population  \
Continent     Country
Africa        Algeria            44903225.0       43451666.0       39543154.0
              Angola             35588987.0       33428485.0       28127721.0
              Benin              13352864.0       12643123.0       10932783.0
              Botswana            2630296.0        2546402.0        2305171.0
              Burkina Faso       22673762.0       21522626.0       18718019.0
...                                     ...              ...              ...
South America Paraguay            6780744.0        6618695.0        6177950.0
              Peru               34049588.0       33304756.0       30711863.0
              Suriname             618040.0         607065.0         575475.0
              Uruguay             3422794.0        3429086.0        3402818.0
              Venezuela          28301696.0       28490453.0       30529716.0

                            2010 Population  2000 Population  1990 Population  \
Continent     Country
Africa        Algeria            35856344.0       30774621.0       25518074.0
              Angola             23364185.0       16394062.0       11828638.0
              Benin               9445710.0        6998023.0        5133419.0
              Botswana            2091664.0        1726985.0        1341474.0
              Burkina Faso       16116845.0       11882888.0        9131361.0
...                                     ...              ...              ...
South America Paraguay            5768613.0        5123819.0        4059195.0
              Peru               29229572.0       26654439.0       22109099.0
              Suriname             546080.0         478998.0         412756.0
              Uruguay             3352651.0        3292224.0        3117012.0
              Venezuela          28715022.0              NaN       19750579.0

                            1980 Population  1970 Population  Area (km²)  \
Continent     Country
Africa        Algeria            18739378.0       13795915.0   2381741.0
              Angola              8330047.0        6029700.0   1246700.0
              Benin               3833939.0        3023443.0    112622.0
              Botswana             938578.0         592244.0    582000.0
              Burkina Faso        6932967.0        5611666.0    272967.0
...                                     ...              ...         ...
South America Paraguay            3078912.0        2408787.0    406752.0
              Peru               17492406.0       13562371.0   1285216.0
              Suriname             375112.0         379918.0    163820.0
              Uruguay             2953750.0        2790265.0    181034.0
              Venezuela          15210443.0       11355475.0         NaN

                            Density (per km²)  Growth Rate  \
Continent     Country
Africa        Algeria                 18.8531       1.0164
              Angola                  28.5466       1.0315
              Benin                  118.5635       1.0274
              Botswana                 4.5194       1.0162
              Burkina Faso            83.0641       1.0259
...                                       ...          ...
South America Paraguay                16.6705       1.0115
              Peru                    26.4933       1.0099
              Suriname                 3.7727       1.0082
              Uruguay                 18.9069       0.9990
              Venezuela               30.8820       1.0036

                            World Population Percentage
Continent     Country
Africa        Algeria                              0.56
              Angola                               0.45
              Benin                                0.17
              Botswana                             0.03
              Burkina Faso                         0.28
...                                                 ...
South America Paraguay                             0.09
              Peru                                 0.43
              Suriname                             0.01
              Uruguay                              0.04
              Venezuela                            0.35

[234 rows x 16 columns]

<div dir="rtl" style="text-align: right;">
6
.الوصول الى البيانات
 </div>

<div dir="rtl" style="text-align: right;">

 بالتسمية (Label-based)
 </div>

<div dir="rtl" style="text-align: right;">
6.1 الوصول الى البيانات من خلال تحديد قيمة ضمن صف معين
 </div>

In [11]:
df.loc["Africa"]

,Rank,CCA3,Capital,Average,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (km²),Density (per km²),Growth Rate,World Population Percentage
Country,,,,,,,,,,,,,,,,
Algeria,34,DZA,Algiers,3.157280e+07,44903225.0,43451666.0,39543154.0,35856344.0,30774621.0,25518074.0,18739378.0,13795915.0,2381741.0,18.8531,1.0164,0.56
Angola,42,AGO,Luanda,2.038648e+07,35588987.0,33428485.0,28127721.0,23364185.0,16394062.0,11828638.0,8330047.0,6029700.0,1246700.0,28.5466,1.0315,0.45
Benin,77,BEN,Porto-Novo,8.170413e+06,13352864.0,12643123.0,10932783.0,9445710.0,6998023.0,5133419.0,3833939.0,3023443.0,112622.0,118.5635,1.0274,0.17
Botswana,144,BWA,Gaborone,1.771602e+06,2630296.0,2546402.0,2305171.0,2091664.0,1726985.0,1341474.0,938578.0,592244.0,582000.0,4.5194,1.0162,0.03
Burkina Faso,58,BFA,Ouagadougou,1.407377e+07,22673762.0,21522626.0,18718019.0,16116845.0,11882888.0,9131361.0,6932967.0,5611666.0,272967.0,83.0641,1.0259,0.28
Burundi,78,BDI,Bujumbura,8.070710e+06,12889576.0,12220227.0,10727148.0,9126605.0,6307659.0,5483793.0,4312834.0,3497834.0,27834.0,463.0874,1.0270,0.16
Cameroon,53,CMR,Yaounde,1.734889e+07,27914536.0,26491087.0,23012646.0,19878036.0,15091594.0,11430520.0,8519891.0,6452787.0,475442.0,58.7128,1.0263,0.35
Cape Verde,171,CPV,Praia,4.595596e+05,593149.0,582640.0,552166.0,521212.0,458251.0,364563.0,317234.0,287262.0,4033.0,147.0739,1.0089,0.01
Central African Republic,117,CAF,Bangui,3.931573e+06,5579144.0,5343020.0,4819333.0,4660067.0,3759170.0,2809221.0,2415276.0,2067356.0,622984.0,8.9555,1.0224,0.07
Chad,69,TCD,N'Djamena,1.032061e+07,17723315.0,16644701.0,14140274.0,11894727.0,8259137.0,5827069.0,4408230.0,3667394.0,1284000.0,13.8032,1.0316,0.22
Comoros,163,COM,Moroni,5.709670e+05,836774.0,806166.0,730216.0,656024.0,536758.0,431119.0,328328.0,242351.0,1862.0,449.3953,1.0184,0.01
Djibouti,160,DJI,Djibouti,7.405211e+05,1120849.0,1090156.0,1006259.0,919199.0,742033.0,577173.0,324121.0,144379.0,23200.0,48.3125,1.0138,0.01
DR Congo,15,COD,Kinshasa,5.854698e+07,99010212.0,92853164.0,78656904.0,66391257.0,48616317.0,35987541.0,26708686.0,20151733.0,2344858.0,42.2244,1.0325,1.24
Egypt,14,EGY,Cairo,7.631850e+07,110990103.0,107465134.0,97723799.0,87252413.0,71371371.0,57214630.0,43748556.0,34781986.0,1002450.0,110.7188,1.0158,1.39
Equatorial Guinea,152,GNQ,Malabo,8.736387e+05,1674908.0,1596049.0,NaN,1094524.0,684977.0,465549.0,282509.0,316955.0,28051.0,59.7094,1.0247,0.02
Eritrea,132,ERI,Asmara,2.650150e+06,3684032.0,3555868.0,3340006.0,3147727.0,2392880.0,2149960.0,1657982.0,1272748.0,117600.0,31.3268,1.0176,0.05
Eswatini,159,SWZ,Mbabane,9.057781e+05,NaN,1180655.0,1133936.0,1099920.0,1030496.0,854011.0,598564.0,442865.0,17364.0,69.2047,1.0079,0.02
Ethiopia,12,ETH,Addis Ababa,7.630552e+07,123379924.0,117190911.0,102471895.0,89237791.0,67031867.0,47878073.0,34945469.0,28308246.0,1104300.0,111.7268,1.0257,1.55
Gabon,146,GAB,Libreville,1.502928e+06,2388992.0,2292573.0,2028517.0,1711105.0,1272935.0,983028.0,749078.0,597192.0,267668.0,8.9252,1.0204,0.03
Gambia,142,GMB,Banjul,2.511040e+06,2705992.0,2573995.0,2253133.0,NaN,NaN,NaN,NaN,NaN,10689.0,253.1567,1.0250,0.03
Ghana,47,GHA,Accra,2.199269e+07,33475870.0,32180401.0,28870939.0,25574719.0,19665502.0,15446982.0,11865246.0,8861895.0,238533.0,140.3406,1.0196,0.42
Guinea,75,GIN,Conakry,9.105914e+06,13859341.0,13205153.0,11625998.0,10270728.0,8336967.0,6354145.0,4972609.0,4222374.0,245857.0,56.3716,1.0242,0.17
Guinea-Bissau,149,GNB,Bissau,1.388132e+06,2105566.0,2015828.0,1788919.0,1567220.0,1230849.0,973551.0,831462.0,591663.0,36125.0,58.2856,1.0218,0.03
Ivory Coast,52,CIV,Yamoussoukro,1.777253e+07,28160542.0,26811790.0,23596741.0,21120042.0,16799670.0,11910540.0,8303809.0,5477086.0,322463.0,NaN,NaN,0.35
Kenya,27,KEN,Nairobi,3.450709e+07,54027487.0,51985780.0,46851488.0,41517895.0,30851606.0,23162269.0,16187124.0,11473087.0,580367.0,93.0919,1.0193,0.68
Lesotho,147,LSO,Maseru,1.866247e+06,2305825.0,2254100.0,2118521.0,2022747.0,1998630.0,1798997.0,1407672.0,1023481.0,30355.0,75.9620,1.0107,0.03
Liberia,121,LBR,Monrovia,3.440405e+06,5302681.0,5087584.0,4612329.0,4019956.0,2895224.0,2209731.0,1932169.0,1463563.0,111369.0,47.6136,1.0210,0.07
Libya,107,LBY,Tripoli,5.051772e+06,6812341.0,6653942.0,6192235.0,6491988.0,5154790.0,4236983.0,2962720.0,1909177.0,1759540.0,3.8717,1.0114,0.09
Madagascar,50,MDG,Antananarivo,1.851325e+07,29611714.0,28225177.0,24850912.0,21731053.0,16216431.0,11882762.0,8948162.0,6639751.0,587041.0,50.4423,1.0241,0.37
Malawi,62,MWI,Lilongwe,1.288766e+07,20405317.0,19377061.0,16938942.0,14718422.0,11229387.0,9539665.0,6267369.0,4625141.0,118484.0,172.2200,1.0259,0.26
Mali,59,MLI,Bamako,1.389625e+07,22593590.0,21224040.0,18112907.0,15529181.0,11239101.0,8945026.0,7372581.0,6153587.0,1240192.0,18.2178,1.0314,0.28
Mauritania,126,MRT,Nouakchott,2.991293e+06,4736139.0,4498604.0,3946220.0,3419461.0,2695003.0,2006027.0,1506694.0,1122198.0,1030700.0,4.5951,1.0263,0.06
Mauritius,157,MUS,Port Louis,1.158122e+06,1299469.0,1297828.0,1293153.0,1283330.0,1215930.0,1090290.0,954865.0,830115.0,2040.0,636.9946,1.0004,0.02
Mayotte,182,MYT,Mamoudzou,1.790636e+05,326101.0,305587.0,249545.0,211786.0,159215.0,92659.0,52233.0,35383.0,374.0,871.9278,1.0319,0.00
Morocco,40,MAR,Rabat,2.867126e+07,37457971.0,36688772.0,34680458.0,32464865.0,28554415.0,24570814.0,19678444.0,15274351.0,446550.0,83.8830,1.0103,0.47
Mozambique,48,MOZ,Maputo,1.917416e+07,32969517.0,31178239.0,NaN,NaN,17768505.0,13303459.0,11413587.0,8411676.0,801590.0,41.1302,1.0278,0.41
Namibia,145,NAM,Windhoek,1.794587e+06,2567012.0,2489098.0,2282704.0,2099271.0,1819141.0,1369011.0,975994.0,754467.0,825615.0,3.1092,1.0146,0.03
Niger,54,NER,Niamey,1.476918e+07,26207977.0,24333639.0,20128124.0,16647543.0,11622665.0,8370647.0,6173177.0,4669708.0,1267000.0,20.6851,1.0378,0.33
Nigeria,6,NGA,Abuja,1.398005e+08,218541212.0,208327405.0,183995785.0,160952853.0,122851984.0,95214257.0,72951439.0,55569264.0,923768.0,236.5759,1.0241,2.74
Republic of the Congo,114,COG,Brazzaville,3.740072e+06,5970424.0,5702174.0,5064386.0,4437884.0,3134030.0,2385435.0,1829256.0,1396989.0,342000.0,17.4574,1.0231,0.07
Reunion,161,REU,Saint-Denis,7.768142e+05,974052.0,957822.0,922495.0,890130.0,785424.0,658992.0,551674.0,473925.0,2511.0,387.9140,1.0082,0.01
Rwanda,76,RWA,Kigali,9.181112e+06,13776698.0,13146362.0,11642959.0,10309031.0,8109989.0,7319962.0,5247532.0,3896367.0,26338.0,523.0731,1.0234,0.17
Sao Tome and Principe,187,STP,São Tomé,1.585166e+05,227380.0,218641.0,201124.0,182138.0,143714.0,120343.0,97210.0,77583.0,964.0,235.8714,1.0192,0.00
Senegal,72,SEN,Dakar,1.099385e+07,17316449.0,16436119.0,14356181.0,12530121.0,9704287.0,7536001.0,5703869.0,4367744.0,NaN,NaN,1.0261,0.22
Seychelles,196,SYC,Victoria,8.438538e+04,107118.0,105530.0,99240.0,92409.0,80060.0,71057.0,65290.0,54379.0,452.0,236.9867,1.0061,0.00
Sierra Leone,102,SLE,Freetown,5.705831e+06,8605718.0,8233969.0,7314773.0,6436698.0,4584067.0,4325388.0,3367477.0,2778557.0,71740.0,119.9570,1.0220,0.11
Somalia,70,SOM,Mogadishu,1.164827e+07,17597511.0,16537016.0,13763906.0,12026649.0,8721465.0,6999096.0,5892224.0,NaN,637657.0,27.5971,1.0312,0.22
South Africa,24,ZAF,Pretoria,4.560999e+07,59893885.0,58801927.0,55876504.0,51784921.0,46813266.0,39877570.0,29463549.0,22368306.0,1221037.0,49.0517,1.0084,0.75
South Sudan,86,SSD,Juba,7.301910e+06,10913164.0,10606227.0,11194299.0,NaN,6114440.0,4750817.0,4192011.0,3342410.0,619745.0,17.6091,1.0153,0.14
Sudan,32,SDN,Khartoum,2.982428e+07,46874204.0,44440486.0,38171178.0,33739933.0,26298773.0,21090886.0,16673586.0,11305206.0,1886068.0,24.8529,1.0267,0.59
Tanzania,22,TZA,Dodoma,3.980515e+07,65497748.0,61704518.0,52542823.0,45110527.0,34463704.0,26206012.0,19297659.0,13618192.0,945087.0,69.3034,1.0300,0.82
Togo,100,TGO,Lomé,5.656980e+06,8848699.0,8442580.0,7473229.0,6571855.0,5008035.0,3875947.0,2838110.0,2197383.0,56785.0,155.8281,1.0236,0.11
Tunisia,79,TUN,Tunis,9.616198e+06,12356117.0,12161723.0,11557779.0,10895063.0,9893316.0,8440023.0,6578156.0,5047404.0,163610.0,75.5218,1.0076,0.15
Uganda,31,UGA,Kampala,2.833523e+07,47249585.0,44404611.0,37477356.0,32341728.0,24020697.0,17586630.0,13284026.0,10317212.0,241550.0,195.6100,1.0304,0.59
Western Sahara,172,ESH,El Aaiún,3.349005e+05,575986.0,556048.0,491824.0,413296.0,270375.0,178529.0,116775.0,76371.0,266000.0,2.1654,1.0184,0.01
Zambia,63,ZMB,Lusaka,1.147387e+07,20017675.0,18927715.0,NaN,13792086.0,9891136.0,7686401.0,5720438.0,4281671.0,752612.0,26.5976,1.0280,0.25
Zimbabwe,74,ZWE,Harare,1.164829e+07,16320537.0,15669666.0,14154937.0,12839771.0,11834676.0,10113893.0,7049926.0,5202918.0,390757.0,41.7665,1.0204,0.20

<div dir="rtl" style="text-align: right;">
6.2 الوصول للبيانات وفق الفهرسة المركبة من خلال تحديد عمودين
 </div>

In [12]:
df.loc[("Africa", "Algeria")]

Rank                                    34
CCA3                                   DZA
Capital                            Algiers
Average                        31572797.13
2022 Population                 44903225.0
2020 Population                 43451666.0
2015 Population                 39543154.0
2010 Population                 35856344.0
2000 Population                 30774621.0
1990 Population                 25518074.0
1980 Population                 18739378.0
1970 Population                 13795915.0
Area (km²)                       2381741.0
Density (per km²)                  18.8531
Growth Rate                         1.0164
World Population Percentage           0.56
Name: (Africa, Algeria), dtype: object

<div dir="rtl" style="text-align: right;">
6.2 الوصول لقيمة محددة وفق الفهرسة المركبة بإستخدام loc من خلال التسمية
 </div>

In [13]:
df.loc[("Africa", "Algeria"), "1990 Population"]

np.float64(25518074.0)

<div dir="rtl" style="text-align: right;">
6.3 الوصول لقيمة محددة وفق الفهرسة المركبة بإستخدام at من خلال التسمية
 </div>

In [14]:
df.at[("Africa", "Algeria"), "1990 Population"]

np.float64(25518074.0)

<div dir="rtl" style="text-align: right;">
إعادة الفهرس إلى العمود الإفتراضي مع الإبقاء على الفهرس القديم
 </div>

In [15]:
df.reset_index(drop=False, inplace=True)
df.head()

,Continent,Country,Rank,CCA3,Capital,Average,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (km²),Density (per km²),Growth Rate,World Population Percentage
0,Asia,Afghanistan,36,AFG,Kabul,2.444019e+07,41128771.0,38972230.0,33753499.0,28189672.0,19542982.0,10694796.0,12486631.0,10752971.0,652230.0,63.0587,1.0257,0.52
1,Europe,Albania,138,ALB,Tirana,2.906065e+06,2842321.0,2866849.0,2882481.0,2913399.0,3182021.0,3295066.0,2941651.0,2324731.0,28748.0,98.8702,0.9957,0.04
2,Africa,Algeria,34,DZA,Algiers,3.157280e+07,44903225.0,43451666.0,39543154.0,35856344.0,30774621.0,25518074.0,18739378.0,13795915.0,2381741.0,18.8531,1.0164,0.56
3,Oceania,American Samoa,213,ASM,Pago Pago,4.533600e+04,44273.0,46189.0,51368.0,54849.0,58230.0,47818.0,32886.0,27075.0,199.0,222.4774,0.9831,0.00
4,Europe,Andorra,203,AND,Andorra la Vella,5.949075e+04,79824.0,77700.0,71746.0,71519.0,66097.0,53569.0,35611.0,19860.0,468.0,170.5641,1.0100,0.00



<div dir="rtl" style="text-align: right;">
6.4 الوصول الى قيمة محددة من خلال تحديد التسمية باستخدام at
 </div>

In [18]:
df.at[2,'Capital']

'Algiers'

<div dir="rtl" style="text-align: right;">
6.5 الوصول الى بيانات صف من خلال الموقع الرقمي للصف
 </div>

In [19]:
df.iloc[2]

Continent                           Africa
Country                            Algeria
Rank                                    34
CCA3                                   DZA
Capital                            Algiers
Average                        31572797.13
2022 Population                 44903225.0
2020 Population                 43451666.0
2015 Population                 39543154.0
2010 Population                 35856344.0
2000 Population                 30774621.0
1990 Population                 25518074.0
1980 Population                 18739378.0
1970 Population                 13795915.0
Area (km²)                       2381741.0
Density (per km²)                  18.8531
Growth Rate                         1.0164
World Population Percentage           0.56
Name: 2, dtype: object


<div dir="rtl" style="text-align: right;">
6.6 الوصول الى قيمة عمود محدد لصف معين وفق الموقع الرقمي
 </div>

In [20]:
df.loc[2, 'Growth Rate']

np.float64(1.0164)

In [22]:
df.loc[2, ['Country', '2022 Population']]

Country               Algeria
2022 Population    44903225.0
Name: 2, dtype: object

<div dir="rtl" style="text-align: right;">
6.7 الوصول الى  أكثر من صف وأكثر من عمود من خلال تحديد الموقع الرقمي


 </div>

In [23]:
df.iloc[0:5, 0:4]

  Continent         Country  Rank CCA3
0      Asia     Afghanistan    36  AFG
1    Europe         Albania   138  ALB
2    Africa         Algeria    34  DZA
3   Oceania  American Samoa   213  ASM
4    Europe         Andorra   203  AND



<div dir="rtl" style="text-align: right;">
6.8 الوصول الى قيمة محددة من خلال تحديد الموقع الرقمي باستخدام iat
 </div>

In [24]:
df.iat[2,4]

'Algiers'