

<div dir="rtl" style="text-align: right;">

## Pandas Course الدرس الثالث 3
 </div>


<div dir="rtl" style="text-align: right;">

## Data Cleaning تنظيف البيانات
 </div>


<div dir="rtl" style="text-align: right;">
استيراد المكتبة

 </div>

In [1]:
import pandas as pd


<div dir="rtl" style="text-align: right;">
0. قراءة الملف


 </div>

In [2]:
df = pd.read_csv(r"D:\Pandas\Pandas_Course\sales_dataset.csv")

<div dir="rtl" style="text-align: right;">
1. مرحلة استكشاف البيانات
 </div>

<div dir="rtl" style="text-align: right;">
1.1 معاينة اول 5 صفوف

 </div>

In [3]:
df.head()

,Customer_ID,First_Name,Last_Name,Gender,Age,Email,Phone_Number,Address,State,Zip_Code,...,Avg_Discount_Used,Total_Refund_Amount,Monthly_Spending_Estimate,Shipping_Distance_KM,Complaints_Count,Preferred_Contact_Time,Customer_Tier,Communication_Preference,Favorite_Product_Category,Special_Notes
0,e3e70682-c209-4cac-a29f-6fbed82c07cd,Lisa,/Davidson,M,62.0,invalid@,NaN,"376 Sullivan Pines, NC, 79174",NaN,NaN,...,3.562214,5.401992,6.006604,4.952193,14.583099,Evening,Bronze,SMS,Clothing,NaN
1,f728b4fa-4248-4e3a-8a5d-2f346baa9455,Crystal,/Atkins,M,65.0,noemail,318.700.3947,"335 Justin Falls Apt. 281, NC, 44166",NaN,NaN,...,-3.469217,6.153640,16.167151,-9.268747,-7.374091,Evening,Bronze,NaN,NaN,Long-Term
2,eb1167b3-67a9-4378-bc65-c1e582e2e662,Deborah,...Moore,F,18.0,melissabell@example.com,...831-909-1619,"19005 Young Divide, FL, 54121",NaN,NaN,...,9.471970,13.200408,4.778315,0.647364,0.999436,NaN,NaN,Phone,NaN,VIP
3,f7c1bd87-4da5-4709-9471-3d60c8a70639,Christopher,/Peterson,F,21.0,invalid@,(708)5821623x24820,"7395 Daniel Station Suite 245, NC, 99335",NaN,NaN,...,NaN,9.748243,0.101264,12.803364,-18.864007,NaN,NaN,SMS,Home,NaN
4,e443df78-9558-467f-9ba9-1faf7a024204,Anna,/Garrett,M,21.0,donna20@example.org,(224)492-5094,"5272 Krista Street, FL, 81468",NaN,NaN,...,2.202235,-19.253180,-17.898067,5.589338,6.346641,Afternoon,NaN,Email,Home,New Customer

<div dir="rtl" style="text-align: right;">
1.2 معاينة اخر 5 صفوف

 </div>

In [4]:
df.tail()

,Customer_ID,First_Name,Last_Name,Gender,Age,Email,Phone_Number,Address,State,Zip_Code,...,Avg_Discount_Used,Total_Refund_Amount,Monthly_Spending_Estimate,Shipping_Distance_KM,Complaints_Count,Preferred_Contact_Time,Customer_Tier,Communication_Preference,Favorite_Product_Category,Special_Notes
5042,3c669aa5-50bb-41c7-b01c-ccc7bb87c961,Darlene,Olson,M,52.0,newtonlaura@example.net,19204471045,"95410 Ellen Road Apt. 972, CA, 76785",NaN,NaN,...,-0.243912,8.135926,-1.500113,-12.749877,NaN,NaN,Platinum,Email,Home,Long-Term
5043,1e8e2d52-2ab9-4185-9af0-ed2850bea76b,Sean,...Espinoza,Female,35.0,invalid@,459.716.5051,"937 Devin Flats, NV, 18768",NaN,NaN,...,8.212205,6.309697,-9.338165,10.851671,-1.599371,Morning,Bronze,Phone,Home,New Customer
5044,9be6a1c7-3882-4ff2-a569-30b895b30690,Gabrielle,/Walton,M,68.0,NaN,(687)704-4501x0011,"9316 Martinez Ways, NC, 04007",NaN,NaN,...,9.285077,4.776145,-16.760514,-2.172965,-23.922515,NaN,Platinum,Phone,Sports,NaN
5045,fb813983-106f-42ec-8896-c62cb397b350,Caitlin,...Smith,Female,55.0,sullivangabriel@example.net,+14552621810x68759,"47631 Adams Cliffs Apt. 603, WA, 68791",NaN,NaN,...,3.804181,-11.619905,2.801931,6.349934,-1.824962,NaN,Platinum,Phone,Electronics,NaN
5046,3c669aa5-50bb-41c7-b01c-ccc7bb87c961,Darlene,Olson,M,52.0,newtonlaura@example.net,19204471045,"95410 Ellen Road Apt. 972, CA, 76785",NaN,NaN,...,-0.243912,8.135926,-1.500113,-12.749877,NaN,NaN,Platinum,Email,Home,Long-Term

<div dir="rtl" style="text-align: right;">
1.3 معاينة عينة عشوائية من البيانات
 </div>

In [5]:
df.sample(20)

,Customer_ID,First_Name,Last_Name,Gender,Age,Email,Phone_Number,Address,State,Zip_Code,...,Avg_Discount_Used,Total_Refund_Amount,Monthly_Spending_Estimate,Shipping_Distance_KM,Complaints_Count,Preferred_Contact_Time,Customer_Tier,Communication_Preference,Favorite_Product_Category,Special_Notes
1864,b2db458c-c4fc-4cd0-a78d-1e08fc4358e5,Cassandra,/Shelton,Female,67.0,NaN,12069429837,"550 Wright Forest Apt. 905, AZ, 74678",NaN,NaN,...,21.992479,5.657858,-16.003128,19.289764,3.980217,Morning,Gold,SMS,Electronics,Long-Term
2982,7d97613f-433c-480a-9b3c-9c49177677c7,James,Garcia__,Female,44.0,NaN,NaN,"288 Adams Coves Apt. 894, CA, 97343",NaN,NaN,...,4.234801,-187.605420,5.218571,-9.483685,15.190698,NaN,Platinum,Email,Clothing,NaN
2572,28dff27a-30c6-4647-ba5d-92dc6db8b178,Kristin,Leonard,Male,NaN,NaN,+1-755-331-9241x28086,"5121 Barnett Village, WA, 09446",NaN,NaN,...,3.010685,1.078978,7.640083,21.643749,-1.594322,NaN,NaN,NaN,Electronics,Long-Term
2518,9619a3e8-dad7-4570-9c21-8083799f0f96,Latoya,...Roach,M,32.0,scottmatthew@example.com,...001-891-592-6919x75978,"93723 Brown Isle, NV, 42687",NaN,NaN,...,NaN,4.522517,-1.236214,1.182046,-5.179489,NaN,NaN,SMS,Clothing,New Customer
4040,b5c7dfc6-4af5-4df3-9148-867a65698eaa,Richard,...Mendoza,F,51.0,tammy45@example.net,NaN,"7134 Ross Locks Suite 652, FL, 67521",NaN,NaN,...,-6.312267,11.693969,-2.335666,19.543282,NaN,Morning,Silver,Email,Clothing,Long-Term
2002,d561d047-914d-477e-8ff0-f84c38137f83,Louis,/Sexton,F,48.0,fsampson@example.org,Na--,"98724 Stephanie Station Suite 277, CA, 90144",NaN,NaN,...,24.282104,-15.097826,-9.780041,-1.323237,3.183555,NaN,Platinum,NaN,Clothing,NaN
3230,2751d213-0027-4097-b10f-835c81fa55ad,Debra,...Moore,Female,55.0,bradyarthur@example.net,Na--,"2534 Peterson Islands, CA, 60972",NaN,NaN,...,8.069542,-3.801378,-3.917464,-7.211751,10.052883,Morning,NaN,NaN,Electronics,NaN
1099,53e82886-9411-423a-90b4-17eb7111f1d1,David,Thomas__,Female,44.0,maria69@example.net,...001-225-741-5314x016,"89218 Rhodes Junctions, NC, 36942",NaN,NaN,...,17.466109,6.506348,1.622821,2.008848,NaN,Morning,NaN,SMS,Clothing,VIP
569,a1ee691a-09e1-43b0-a71f-27728d7f7ba5,Angelica,...Valdez,,52.0,NaN,001-336-401-2730x91213,"57527 Melanie Isle Apt. 179, CA, 47790",NaN,NaN,...,-13.643523,22.610388,-0.487601,1.250812,-4.298544,Afternoon,Gold,Phone,Beauty,VIP
703,820bc51d-db3a-4fa6-87d0-286213f36e53,Anita,Boyd,M,55.0,joshua70@example.com,(965)3025424,"95856 Krista Parks Suite 302, AZ, 42468",NaN,NaN,...,-5.401254,10.820275,7.331362,1.222483,-9.175528,Evening,Platinum,Phone,Electronics,VIP
4869,271f08e7-d0b1-4290-a4a1-fc766994b61b,Paul,Bowen__,Male,57.0,NaN,NaN,"191 Graham Roads, CA, 00684",NaN,NaN,...,2.671949,-1.654689,-2.322275,-14.803048,1.068959,NaN,Platinum,NaN,Home,Long-Term
4916,b61f8d90-35f6-40e9-adaa-37f7791bcee8,Michael,/Jackson,Female,51.0,NaN,...983.923.8760x1048,"5447 Young Walk Apt. 134, TX, 86558",NaN,NaN,...,17.371643,10.437035,16.159018,-15.630206,-1.327167,Evening,Platinum,Email,Clothing,Long-Term
3730,aff3cc60-a7a2-4842-9ac5-13d314d0f793,Jennifer,/Johnson,M,57.0,NaN,402-774-7936,"984 Barker Spurs Suite 849, FL, 30657",NaN,NaN,...,-5.775485,-11.927847,-393.108545,-1.732048,-5.307182,Afternoon,Silver,NaN,Home,New Customer
995,dbb59fc2-5cff-496e-bd03-c81f7ff35029,Vanessa,...Jennings,,54.0,invalid@,nan--,"326 Snyder Mill, NV, 33287",NaN,NaN,...,-14.902795,1.061654,3.849864,-8.866073,3.654187,NaN,NaN,SMS,Beauty,NaN
4994,b872b60c-fa4e-40e4-9c1c-516aea8598eb,Cody,...Greer,M,51.0,NaN,Na--,"182 Derrick Centers Suite 248, CA, 50808",NaN,NaN,...,2.921030,32.377577,-3.890572,-1.137691,16.687346,Morning,Gold,NaN,Sports,New Customer
2873,fb5c8295-a67d-49d6-b087-479fc11bd09f,Shawn,Perry__,Female,32.0,NaN,Na--,"27657 Jackson Brooks, NV, 09538",NaN,NaN,...,24.031605,11.660629,4.631324,-10.606758,24.047876,Morning,Platinum,Phone,Beauty,NaN
4337,09d1a23b-41ed-4ad7-b799-e29648d44935,Jennifer,...Guzman,F,20.0,michellebryant@example.net,nan--,"98683 May Dam Suite 549, WA, 69880",NaN,NaN,...,-6.190035,-6.518610,-203.129702,-3.629958,NaN,Morning,Gold,NaN,Clothing,New Customer
412,27be0381-6544-497d-a078-9f97213c121c,Daniel,Mcdowell__,F,36.0,invalid@,(364)4703754x322,"7952 Dawn Rue Apt. 161, NV, 18502",NaN,NaN,...,21.311949,-7.566336,2.502055,0.799487,-17.313345,Afternoon,NaN,Phone,Beauty,NaN
4530,8f4d77a5-cbe7-4002-b6f7-15caa59db0ac,Todd,...Frazier,Female,39.0,invalid@,Na--,"9746 Nicole Tunnel, WA, 83208",NaN,NaN,...,0.016630,2.899743,-3.032045,5.135876,-9.479717,Evening,Bronze,Phone,Sports,Long-Term
3897,c6150907-d3f4-4a2e-b5ad-03adae971471,Dennis,Odom,Male,45.0,angelacase@example.org,NaN,"193 Sabrina Gardens, WA, 51386",NaN,NaN,...,9.247140,2.922393,-6.369799,2.644076,-6.821287,NaN,Silver,Phone,Sports,NaN

<div dir="rtl" style="text-align: right;">
1.4 عرض معلومات هيكلية عن البيانات

 </div>

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5047 entries, 0 to 5046
Data columns (total 42 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Customer_ID                   5047 non-null   object
 1   First_Name                    5047 non-null   object
 2   Last_Name                     5047 non-null   object
 3   Gender                        5047 non-null   object
 4   Age                           4978 non-null   float64
 5   Email                         4025 non-null   object
 6   Phone_Number                  4178 non-null   object
 7   Address                       5047 non-null   object
 8   State                         0 non-null      float64
 9   Zip_Code                      0 non-null      float64
 10  Join_Date                     5047 non-null   object
 11  Last_Purchase_Date            5047 non-null   object
 12  Category                      5047 non-null   object
 13  Product_Name                  5047 non-null   object
 14  Quantity                      4936 non-null   float64
 15  Unit_Price                    5047 non-null   object
 16  Purchase_Amount               0 non-null      float64
 17  Payment_Method                5047 non-null   object
 18  Sales_Channel                 5047 non-null   object
 19  Do_Not_Contact                3907 non-null   object
 20  Customer_Status               5047 non-null   object
 21  Satisfaction_Rating           5047 non-null   int64
 22  Notes                         3338 non-null   object
 23  Is_Returned                   5047 non-null   object
 24  Return_Reason                 4075 non-null   object
 25  Employee_Assigned             5047 non-null   object
 26  Not_Useful_Column             2993 non-null   object
 27  Total_Visits_Last_Year        4795 non-null   float64
 28  Avg_Session_Duration_Minutes  4795 non-null   float64
 29  Total_Clicks_On_Ads           4795 non-null   float64
 30  Credit_Score                  4795 non-null   float64
 31  Loyalty_Points                4795 non-null   float64
 32  Avg_Discount_Used             4795 non-null   float64
 33  Total_Refund_Amount           4795 non-null   float64
 34  Monthly_Spending_Estimate     4795 non-null   float64
 35  Shipping_Distance_KM          4795 non-null   float64
 36  Complaints_Count              4794 non-null   float64
 37  Preferred_Contact_Time        3008 non-null   object
 38  Customer_Tier                 3979 non-null   object
 39  Communication_Preference      3003 non-null   object
 40  Favorite_Product_Category     4216 non-null   object
 41  Special_Notes                 3014 non-null   object
dtypes: float64(15), int64(1), object(26)
memory usage: 1.6+ MB

<div dir="rtl" style="text-align: right;">
1.5 معرفة حجم البيانات عدد الصفوف والأعمدة


 </div>

In [9]:
df.shape

(5047, 42)

<div dir="rtl" style="text-align: right;">
1.6 الإحصائيات الوصفية للأعمدة الرقمية

 </div>

In [10]:
df.describe()

,Age,State,Zip_Code,Quantity,Purchase_Amount,Satisfaction_Rating,Total_Visits_Last_Year,Avg_Session_Duration_Minutes,Total_Clicks_On_Ads,Credit_Score,Loyalty_Points,Avg_Discount_Used,Total_Refund_Amount,Monthly_Spending_Estimate,Shipping_Distance_KM,Complaints_Count
count,4978.000000,0.0,0.0,4936.000000,0.0,5047.000000,4795.000000,4795.000000,4795.000000,4795.000000,4795.000000,4795.000000,4795.000000,4795.000000,4795.000000,4794.000000
mean,43.758136,NaN,NaN,50.057739,NaN,2.985140,0.028278,0.781094,0.526329,0.330326,-0.723764,0.354489,0.224604,0.377136,0.104236,0.450216
std,20.683240,NaN,NaN,28.678706,NaN,1.417844,56.018648,59.989753,50.946311,48.156139,47.547647,54.902650,47.644505,48.358295,49.618027,47.522334
min,0.000000,NaN,NaN,1.000000,NaN,1.000000,-1111.327792,-1322.809791,-1071.325284,-1046.133036,-1249.392327,-968.039402,-1299.160013,-1027.386612,-1267.937611,-1107.006646
25%,30.000000,NaN,NaN,25.000000,NaN,2.000000,-6.855269,-6.647016,-7.130072,-6.874914,-7.131306,-6.803825,-6.345657,-7.008145,-7.168125,-6.861263
50%,44.000000,NaN,NaN,50.000000,NaN,3.000000,0.041113,0.254249,-0.359840,0.144279,-0.056336,-0.024936,0.463644,-0.240837,-0.229058,-0.122154
75%,57.000000,NaN,NaN,75.000000,NaN,4.000000,6.778520,7.139107,6.307617,6.903459,6.870544,6.909566,7.255531,6.685382,6.694810,6.581094
max,1010.000000,NaN,NaN,100.000000,NaN,5.000000,1747.671114,1167.249572,1352.083863,1024.405946,862.195644,1224.201197,885.107005,1388.821623,876.999643,933.702983


<div dir="rtl" style="text-align: right;">
2 مرحلة معالجة البيانات - تنظيف البيانات
 </div>


<div dir="rtl" style="text-align: right;">
معالجة القيم المكررة Duplicate Values Handling
 </div>


<div dir="rtl" style="text-align: right;">
2.1 الكشف عن وجود القيم المكررة و عددها

 </div>

In [11]:
df.duplicated().sum()

np.int64(4)


<div dir="rtl" style="text-align: right;">
2.2 معرفة اسماء الأعمدة التي يوجد فيها قيم مكررة
 </div>

In [12]:
duplicate_column = []

for col in df.columns:
    if df[col].duplicated().any():
            duplicate_column.append(col)

print(duplicate_column)

['Customer_ID', 'First_Name', 'Last_Name', 'Gender', 'Age', 'Email', 'Phone_Number', 'Address', 'State', 'Zip_Code', 'Join_Date', 'Last_Purchase_Date', 'Category', 'Product_Name', 'Quantity', 'Unit_Price', 'Purchase_Amount', 'Payment_Method', 'Sales_Channel', 'Do_Not_Contact', 'Customer_Status', 'Satisfaction_Rating', 'Notes', 'Is_Returned', 'Return_Reason', 'Employee_Assigned', 'Not_Useful_Column', 'Total_Visits_Last_Year', 'Avg_Session_Duration_Minutes', 'Total_Clicks_On_Ads', 'Credit_Score', 'Loyalty_Points', 'Avg_Discount_Used', 'Total_Refund_Amount', 'Monthly_Spending_Estimate', 'Shipping_Distance_KM', 'Complaints_Count', 'Preferred_Contact_Time', 'Customer_Tier', 'Communication_Preference', 'Favorite_Product_Category', 'Special_Notes']


<div dir="rtl" style="text-align: right;">
2.3 عرض البيانات المكررة فقط
 </div>

In [13]:
duplicates = df[df.duplicated(keep=False)].sort_values(by= list(df.columns))

print(duplicates)

                               Customer_ID First_Name    Last_Name  Gender  \
5039  1e8e2d52-2ab9-4185-9af0-ed2850bea76b       Sean  ...Espinoza  Female
5043  1e8e2d52-2ab9-4185-9af0-ed2850bea76b       Sean  ...Espinoza  Female
5042  3c669aa5-50bb-41c7-b01c-ccc7bb87c961    Darlene        Olson       M
5046  3c669aa5-50bb-41c7-b01c-ccc7bb87c961    Darlene        Olson       M
5040  9be6a1c7-3882-4ff2-a569-30b895b30690  Gabrielle      /Walton       M
5044  9be6a1c7-3882-4ff2-a569-30b895b30690  Gabrielle      /Walton       M
5041  fb813983-106f-42ec-8896-c62cb397b350    Caitlin     ...Smith  Female
5045  fb813983-106f-42ec-8896-c62cb397b350    Caitlin     ...Smith  Female

       Age                        Email        Phone_Number  \
5039  35.0                     invalid@        459.716.5051
5043  35.0                     invalid@        459.716.5051
5042  52.0      newtonlaura@example.net         19204471045
5046  52.0      newtonlaura@example.net         19204471045
5040  68.0                          NaN  (687)704-4501x0011
5044  68.0                          NaN  (687)704-4501x0011
5041  55.0  sullivangabriel@example.net  +14552621810x68759
5045  55.0  sullivangabriel@example.net  +14552621810x68759

                                     Address  State  Zip_Code  ...  \
5039              937 Devin Flats, NV, 18768    NaN       NaN  ...
5043              937 Devin Flats, NV, 18768    NaN       NaN  ...
5042    95410 Ellen Road Apt. 972, CA, 76785    NaN       NaN  ...
5046    95410 Ellen Road Apt. 972, CA, 76785    NaN       NaN  ...
5040           9316 Martinez Ways, NC, 04007    NaN       NaN  ...
5044           9316 Martinez Ways, NC, 04007    NaN       NaN  ...
5041  47631 Adams Cliffs Apt. 603, WA, 68791    NaN       NaN  ...
5045  47631 Adams Cliffs Apt. 603, WA, 68791    NaN       NaN  ...

     Avg_Discount_Used Total_Refund_Amount Monthly_Spending_Estimate  \
5039          8.212205            6.309697                 -9.338165
5043          8.212205            6.309697                 -9.338165
5042         -0.243912            8.135926                 -1.500113
5046         -0.243912            8.135926                 -1.500113
5040          9.285077            4.776145                -16.760514
5044          9.285077            4.776145                -16.760514
5041          3.804181          -11.619905                  2.801931
5045          3.804181          -11.619905                  2.801931

     Shipping_Distance_KM  Complaints_Count Preferred_Contact_Time  \
5039            10.851671         -1.599371                Morning
5043            10.851671         -1.599371                Morning
5042           -12.749877               NaN                    NaN
5046           -12.749877               NaN                    NaN
5040            -2.172965        -23.922515                    NaN
5044            -2.172965        -23.922515                    NaN
5041             6.349934         -1.824962                    NaN
5045             6.349934         -1.824962                    NaN

      Customer_Tier Communication_Preference Favorite_Product_Category  \
5039         Bronze                    Phone                      Home
5043         Bronze                    Phone                      Home
5042       Platinum                    Email                      Home
5046       Platinum                    Email                      Home
5040       Platinum                    Phone                    Sports
5044       Platinum                    Phone                    Sports
5041       Platinum                    Phone               Electronics
5045       Platinum                    Phone               Electronics

     Special_Notes
5039  New Customer
5043  New Customer
5042     Long-Term
5046     Long-Term
5040           NaN
5044           NaN
5041           NaN
5045           NaN

[8 rows x 42 columns]


<div dir="rtl" style="text-align: right;">
معرفة ابعاد البيانات
 </div>

In [14]:
df.shape

(5047, 42)


<div dir="rtl" style="text-align: right;">
2.4 حذف البيانات المكررة </div>

In [15]:
df= df.drop_duplicates()


<div dir="rtl" style="text-align: right;">
معرفة ابعاد البيانات بعد حذف الصفوف المكررة

 </div>

In [16]:
df.shape

(5043, 42)


<div dir="rtl" style="text-align: right;">
2.5 حذف القيمة Deleting Values

 </div>


<div dir="rtl" style="text-align: right;">
اظهار اسماء الاعمدة
 </div>

In [17]:
df.columns

Index(['Customer_ID', 'First_Name', 'Last_Name', 'Gender', 'Age', 'Email',
       'Phone_Number', 'Address', 'State', 'Zip_Code', 'Join_Date',
       'Last_Purchase_Date', 'Category', 'Product_Name', 'Quantity',
       'Unit_Price', 'Purchase_Amount', 'Payment_Method', 'Sales_Channel',
       'Do_Not_Contact', 'Customer_Status', 'Satisfaction_Rating', 'Notes',
       'Is_Returned', 'Return_Reason', 'Employee_Assigned',
       'Not_Useful_Column', 'Total_Visits_Last_Year',
       'Avg_Session_Duration_Minutes', 'Total_Clicks_On_Ads', 'Credit_Score',
       'Loyalty_Points', 'Avg_Discount_Used', 'Total_Refund_Amount',
       'Monthly_Spending_Estimate', 'Shipping_Distance_KM', 'Complaints_Count',
       'Preferred_Contact_Time', 'Customer_Tier', 'Communication_Preference',
       'Favorite_Product_Category', 'Special_Notes'],
      dtype='object')

<div dir="rtl" style="text-align: right;">
2.5.1 حذف الأعمدة باستخدام del

 </div>

In [18]:
del df["Not_Useful_Column"]

df.columns

Index(['Customer_ID', 'First_Name', 'Last_Name', 'Gender', 'Age', 'Email',
       'Phone_Number', 'Address', 'State', 'Zip_Code', 'Join_Date',
       'Last_Purchase_Date', 'Category', 'Product_Name', 'Quantity',
       'Unit_Price', 'Purchase_Amount', 'Payment_Method', 'Sales_Channel',
       'Do_Not_Contact', 'Customer_Status', 'Satisfaction_Rating', 'Notes',
       'Is_Returned', 'Return_Reason', 'Employee_Assigned',
       'Total_Visits_Last_Year', 'Avg_Session_Duration_Minutes',
       'Total_Clicks_On_Ads', 'Credit_Score', 'Loyalty_Points',
       'Avg_Discount_Used', 'Total_Refund_Amount', 'Monthly_Spending_Estimate',
       'Shipping_Distance_KM', 'Complaints_Count', 'Preferred_Contact_Time',
       'Customer_Tier', 'Communication_Preference',
       'Favorite_Product_Category', 'Special_Notes'],
      dtype='object')

<div dir="rtl" style="text-align: right;">
2.5.1 حذف الأعمدة باستخدام pop

 </div>

<div dir="rtl" style="text-align: right;">


 </div>

In [19]:
df.pop("Email")
df.head(2)

,Customer_ID,First_Name,Last_Name,Gender,Age,Phone_Number,Address,State,Zip_Code,Join_Date,...,Avg_Discount_Used,Total_Refund_Amount,Monthly_Spending_Estimate,Shipping_Distance_KM,Complaints_Count,Preferred_Contact_Time,Customer_Tier,Communication_Preference,Favorite_Product_Category,Special_Notes
0,e3e70682-c209-4cac-a29f-6fbed82c07cd,Lisa,/Davidson,M,62.0,NaN,"376 Sullivan Pines, NC, 79174",NaN,NaN,1/6/2021,...,3.562214,5.401992,6.006604,4.952193,14.583099,Evening,Bronze,SMS,Clothing,NaN
1,f728b4fa-4248-4e3a-8a5d-2f346baa9455,Crystal,/Atkins,M,65.0,318.700.3947,"335 Justin Falls Apt. 281, NC, 44166",NaN,NaN,5/7/2021,...,-3.469217,6.153640,16.167151,-9.268747,-7.374091,Evening,Bronze,NaN,NaN,Long-Term

<div dir="rtl" style="text-align: right;">
2.5.3 حذف الأعمدة باستخدام drop


 </div>

In [21]:
df = df.drop(["State", "Zip_Code"], axis=1)
df.head(2)

,Customer_ID,First_Name,Last_Name,Gender,Age,Phone_Number,Address,Join_Date,Last_Purchase_Date,Category,...,Avg_Discount_Used,Total_Refund_Amount,Monthly_Spending_Estimate,Shipping_Distance_KM,Complaints_Count,Preferred_Contact_Time,Customer_Tier,Communication_Preference,Favorite_Product_Category,Special_Notes
0,e3e70682-c209-4cac-a29f-6fbed82c07cd,Lisa,/Davidson,M,62.0,NaN,"376 Sullivan Pines, NC, 79174",1/6/2021,8/20/2025,Automotive,...,3.562214,5.401992,6.006604,4.952193,14.583099,Evening,Bronze,SMS,Clothing,NaN
1,f728b4fa-4248-4e3a-8a5d-2f346baa9455,Crystal,/Atkins,M,65.0,318.700.3947,"335 Justin Falls Apt. 281, NC, 44166",5/7/2021,3/25/2025,Beauty,...,-3.469217,6.153640,16.167151,-9.268747,-7.374091,Evening,Bronze,NaN,NaN,Long-Term

<div dir="rtl" style="text-align: right;">
2.5.4 حذف الأعمدة باستخدام drop


 </div>

In [22]:
df = df.drop(columns=["Notes", "Purchase_Amount"])

df.head(2)

,Customer_ID,First_Name,Last_Name,Gender,Age,Phone_Number,Address,Join_Date,Last_Purchase_Date,Category,...,Avg_Discount_Used,Total_Refund_Amount,Monthly_Spending_Estimate,Shipping_Distance_KM,Complaints_Count,Preferred_Contact_Time,Customer_Tier,Communication_Preference,Favorite_Product_Category,Special_Notes
0,e3e70682-c209-4cac-a29f-6fbed82c07cd,Lisa,/Davidson,M,62.0,NaN,"376 Sullivan Pines, NC, 79174",1/6/2021,8/20/2025,Automotive,...,3.562214,5.401992,6.006604,4.952193,14.583099,Evening,Bronze,SMS,Clothing,NaN
1,f728b4fa-4248-4e3a-8a5d-2f346baa9455,Crystal,/Atkins,M,65.0,318.700.3947,"335 Justin Falls Apt. 281, NC, 44166",5/7/2021,3/25/2025,Beauty,...,-3.469217,6.153640,16.167151,-9.268747,-7.374091,Evening,Bronze,NaN,NaN,Long-Term

<div dir="rtl" style="text-align: right;">
2.5.5 حذف الأعمدة باستخدام شرط


 </div>

<div dir="rtl" style="text-align: right;">
استيراد البيانات

 </div>

In [23]:
df1 = pd.read_csv(r"D:\Pandas\Pandas_Course\world_population.csv")
df1.head()

,Rank,CCA3,Country,Capital,Continent,Average,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (km²),Density (per km²),Growth Rate,World Population Percentage
0,36,AFG,Afghanistan,Kabul,Asia,2.444019e+07,41128771.0,38972230.0,33753499.0,28189672.0,19542982.0,10694796.0,12486631.0,10752971.0,652230.0,63.0587,1.0257,0.52
1,138,ALB,Albania,Tirana,Europe,2.906065e+06,2842321.0,2866849.0,2882481.0,2913399.0,3182021.0,3295066.0,2941651.0,2324731.0,28748.0,98.8702,0.9957,0.04
2,34,DZA,Algeria,Algiers,Africa,3.157280e+07,44903225.0,43451666.0,39543154.0,35856344.0,30774621.0,25518074.0,18739378.0,13795915.0,2381741.0,18.8531,1.0164,0.56
3,213,ASM,American Samoa,Pago Pago,Oceania,4.533600e+04,44273.0,46189.0,51368.0,54849.0,58230.0,47818.0,32886.0,27075.0,199.0,222.4774,0.9831,0.00
4,203,AND,Andorra,Andorra la Vella,Europe,5.949075e+04,79824.0,77700.0,71746.0,71519.0,66097.0,53569.0,35611.0,19860.0,468.0,170.5641,1.0100,0.00

In [24]:
df1 = df1[[col for col in df1.columns if "Population" not in col]]

df1.head()

,Rank,CCA3,Country,Capital,Continent,Average,Area (km²),Density (per km²),Growth Rate
0,36,AFG,Afghanistan,Kabul,Asia,2.444019e+07,652230.0,63.0587,1.0257
1,138,ALB,Albania,Tirana,Europe,2.906065e+06,28748.0,98.8702,0.9957
2,34,DZA,Algeria,Algiers,Africa,3.157280e+07,2381741.0,18.8531,1.0164
3,213,ASM,American Samoa,Pago Pago,Oceania,4.533600e+04,199.0,222.4774,0.9831
4,203,AND,Andorra,Andorra la Vella,Europe,5.949075e+04,468.0,170.5641,1.0100

<div dir="rtl" style="text-align: right;">
2.5.6 حذف الصفوف وفق شرط واحد

 </div>

In [25]:
df["Sales_Channel"]

0       Online
1        Phone
2        Phone
3       Online
4        Store
         ...
5038    Online
5039     Store
5040     Store
5041     Phone
5042     Store
Name: Sales_Channel, Length: 5043, dtype: object

In [26]:
df = df[df["Sales_Channel"] != "Online"]
df["Sales_Channel"]

1       Phone
2       Phone
4       Store
6       Phone
9       Phone
        ...
5037    Phone
5039    Store
5040    Store
5041    Phone
5042    Store
Name: Sales_Channel, Length: 3375, dtype: object

<div dir="rtl" style="text-align: right;">

2.5.7 حذف الصفوف وفق شرطين مختلفين
 </div>

In [27]:
df["Do_Not_Contact"].value_counts()

Do_Not_Contact
Yes    382
No     381
yes    376
y      374
N/a    374
no     372
n      354
Name: count, dtype: int64

In [28]:
df["Is_Returned"].value_counts()

Is_Returned
y      602
no     571
No     561
Yes    559
n      550
yes    532
Name: count, dtype: int64

In [29]:
df = df[~((df["Do_Not_Contact"] == 'y') & (df["Is_Returned"] == 'yes'))]

In [31]:
print(df[["Do_Not_Contact","Is_Returned"]].value_counts())

Do_Not_Contact  Is_Returned
yes             y              79
N/a             y              78
No              y              74
no              No             73
y               n              71
Yes             Yes            70
yes             no             69
no              no             69
y               Yes            68
N/a             yes            67
No              no             66
yes             No             66
Yes             no             66
no              yes            65
y               y              65
No              Yes            65
Yes             y              64
                n              63
n               No             62
                n              62
no              y              61
n               no             61
No              n              61
N/a             n              60
y               no             60
Yes             No             60
                yes            59
no              n              59
y               No             59
No              yes            58
N/a             No             58
                no             58
No              No             57
n               yes            57
                y              57
yes             yes            55
n               Yes            55
yes             n              55
N/a             Yes            53
yes             Yes            52
no              Yes            45
Name: count, dtype: int64

<div dir="rtl" style="text-align: right;">
3 التعامل مع القيم الفارغة Missing Values Handling
 </div>

<div dir="rtl" style="text-align: right;">
3.1 الكشف عن القيم الفارغة
 </div>

In [32]:
df.isnull().sum()

Customer_ID                        0
First_Name                         0
Last_Name                          0
Gender                             0
Age                               40
Phone_Number                     570
Address                            0
Join_Date                          0
Last_Purchase_Date                 0
Category                           0
Product_Name                       0
Quantity                          77
Unit_Price                         0
Payment_Method                     0
Sales_Channel                      0
Do_Not_Contact                   762
Customer_Status                    0
Satisfaction_Rating                0
Is_Returned                        0
Return_Reason                    660
Employee_Assigned                  0
Total_Visits_Last_Year           174
Avg_Session_Duration_Minutes     173
Total_Clicks_On_Ads              169
Credit_Score                     157
Loyalty_Points                   164
Avg_Discount_Used                164
Total_Refund_Amount              170
Monthly_Spending_Estimate        164
Shipping_Distance_KM             171
Complaints_Count                 156
Preferred_Contact_Time          1334
Customer_Tier                    707
Communication_Preference        1342
Favorite_Product_Category        549
Special_Notes                   1310
dtype: int64

In [33]:
df.isna().sum()

Customer_ID                        0
First_Name                         0
Last_Name                          0
Gender                             0
Age                               40
Phone_Number                     570
Address                            0
Join_Date                          0
Last_Purchase_Date                 0
Category                           0
Product_Name                       0
Quantity                          77
Unit_Price                         0
Payment_Method                     0
Sales_Channel                      0
Do_Not_Contact                   762
Customer_Status                    0
Satisfaction_Rating                0
Is_Returned                        0
Return_Reason                    660
Employee_Assigned                  0
Total_Visits_Last_Year           174
Avg_Session_Duration_Minutes     173
Total_Clicks_On_Ads              169
Credit_Score                     157
Loyalty_Points                   164
Avg_Discount_Used                164
Total_Refund_Amount              170
Monthly_Spending_Estimate        164
Shipping_Distance_KM             171
Complaints_Count                 156
Preferred_Contact_Time          1334
Customer_Tier                    707
Communication_Preference        1342
Favorite_Product_Category        549
Special_Notes                   1310
dtype: int64

<div dir="rtl" style="text-align: right;">
3.2 ملء القيم الفارغة بقيمة ثابتة للأعمدة الرقمية

 </div>

In [34]:
df["Total_Visits_Last_Year"] = df["Total_Visits_Last_Year"].fillna(0)
df["Total_Visits_Last_Year"].isna().sum()

np.int64(0)

In [35]:
df.isna().sum()[df.isna().sum() > 0].sort_values(ascending=False)

Communication_Preference        1342
Preferred_Contact_Time          1334
Special_Notes                   1310
Do_Not_Contact                   762
Customer_Tier                    707
Return_Reason                    660
Phone_Number                     570
Favorite_Product_Category        549
Avg_Session_Duration_Minutes     173
Shipping_Distance_KM             171
Total_Refund_Amount              170
Total_Clicks_On_Ads              169
Avg_Discount_Used                164
Monthly_Spending_Estimate        164
Loyalty_Points                   164
Credit_Score                     157
Complaints_Count                 156
Quantity                          77
Age                               40
dtype: int64

<div dir="rtl" style="text-align: right;">
3.3 ملء القيم الفارغة بقيمة ثابتة للأعمدة النصية


 </div>

In [36]:
df["Return_Reason"] = df["Return_Reason"].fillna("not known")
df["Return_Reason"].isna().sum()

np.int64(0)

<div dir="rtl" style="text-align: right;">
3.4 ملء القيم الفارغة بالوسط الحسابي (Mean)

 </div>

In [37]:
df["Quantity"].mean()

np.float64(49.79796735448106)

In [38]:
df["Quantity"] = df["Quantity"].fillna(df["Quantity"].mean())
df["Quantity"].isna().sum()

np.int64(0)

In [39]:
df.isna().sum()[df.isna().sum() > 0].sort_values(ascending=False)

Communication_Preference        1342
Preferred_Contact_Time          1334
Special_Notes                   1310
Do_Not_Contact                   762
Customer_Tier                    707
Phone_Number                     570
Favorite_Product_Category        549
Avg_Session_Duration_Minutes     173
Shipping_Distance_KM             171
Total_Refund_Amount              170
Total_Clicks_On_Ads              169
Monthly_Spending_Estimate        164
Loyalty_Points                   164
Avg_Discount_Used                164
Credit_Score                     157
Complaints_Count                 156
Age                               40
dtype: int64

<div dir="rtl" style="text-align: right;">

3.5 ملء القيم الفارغة بالمنوال (Mode)
 </div>

In [40]:
df["Age"] = df["Age"].fillna(df["Age"].mode()[0])
df["Age"].isna().sum()

np.int64(0)

<div dir="rtl" style="text-align: right;">
3.6 ملء القيم الفارغة بالانحراف المعياري (Standard Deviation)

 </div>

In [41]:
df["Credit_Score"] = df["Credit_Score"].fillna(df["Credit_Score"].std())
df["Credit_Score"].isna().sum()

np.int64(0)

<div dir="rtl" style="text-align: right;">
3.7 ملء القيم الفارغة باستخدام شرط (Conditional Filling)

 </div>

In [42]:
df["Monthly_Spending_Estimate"] = df["Monthly_Spending_Estimate"].fillna(df["Monthly_Spending_Estimate"].apply(lambda x: 3500 if x < 2500 else 400))
df["Monthly_Spending_Estimate"].isna().sum()

np.int64(0)

In [43]:
df.isna().sum()[df.isna().sum() > 0].sort_values(ascending=False)

Communication_Preference        1342
Preferred_Contact_Time          1334
Special_Notes                   1310
Do_Not_Contact                   762
Customer_Tier                    707
Phone_Number                     570
Favorite_Product_Category        549
Avg_Session_Duration_Minutes     173
Shipping_Distance_KM             171
Total_Refund_Amount              170
Total_Clicks_On_Ads              169
Loyalty_Points                   164
Avg_Discount_Used                164
Complaints_Count                 156
dtype: int64

<div dir="rtl" style="text-align: right;">


 </div>

<div dir="rtl" style="text-align: right;">
3.8 تطبيق bfill على أعمدة محددة فقط

 </div>

In [44]:
df['Customer_Tier'] =  df['Customer_Tier'].ffill()
df['Customer_Tier'].isna().sum()

np.int64(0)

<div dir="rtl" style="text-align: right;">


 </div>

In [45]:
df['Preferred_Contact_Time'] = df['Preferred_Contact_Time'].bfill()
df['Preferred_Contact_Time'].isna().sum()

np.int64(3)

<div dir="rtl" style="text-align: right;">


 </div>

In [52]:
df.isna().sum()[df.isna().sum() > 0].sort_values(ascending=False)

Communication_Preference        1342
Do_Not_Contact                   762
Phone_Number                     570
Favorite_Product_Category        549
Avg_Session_Duration_Minutes     173
Shipping_Distance_KM             171
Total_Refund_Amount              170
Total_Clicks_On_Ads              169
Loyalty_Points                   164
Avg_Discount_Used                164
Complaints_Count                 156
Preferred_Contact_Time             3
dtype: int64

In [57]:
cols = ['Communication_Preference',
        "Favorite_Product_Category ",
        "Special_Notes "
]

df[col] = df[col].bfill()

In [58]:
df.isna().sum()[df.isna().sum() > 0].sort_values(ascending=False)

Communication_Preference        1342
Do_Not_Contact                   762
Phone_Number                     570
Favorite_Product_Category        549
Avg_Session_Duration_Minutes     173
Shipping_Distance_KM             171
Total_Refund_Amount              170
Total_Clicks_On_Ads              169
Loyalty_Points                   164
Avg_Discount_Used                164
Complaints_Count                 156
Preferred_Contact_Time             3
dtype: int64

<div dir="rtl" style="text-align: right;">


 </div>

In [59]:
cols = ['Avg_Session_Duration_Minutes', 
        'Shipping_Distance_KM', 
        'Total_Refund_Amount','Total_Clicks_On_Ads',
        'Loyalty_Points',
        'Avg_Discount_Used',
        'Complaints_Count']

for col in cols:
    df[col]= df[col].fillna(df[col].mean())

df.isna().sum()[df.isna().sum() > 0].sort_values(ascending=False)

Communication_Preference     1342
Do_Not_Contact                762
Phone_Number                  570
Favorite_Product_Category     549
Preferred_Contact_Time          3
dtype: int64

<div dir="rtl" style="text-align: right;">

3.9 إزالة القيم الفارغة أو النصوص غير صالحة
 </div>

In [60]:
df['Phone_Number'] = df['Phone_Number'].replace(['Na--', 'nan--', 'None', '<NA>', 'NaN'], pd.NA)

df['Phone_Number']

1                  318.700.3947
2               ...831-909-1619
4                 (224)492-5094
6            527.514.1187x87554
9                          <NA>
                 ...
5037    ...+1-707-377-2898x1578
5039               459.716.5051
5040         (687)704-4501x0011
5041         +14552621810x68759
5042                19204471045
Name: Phone_Number, Length: 3324, dtype: object

<div dir="rtl" style="text-align: right;">
3.10 ازالة كل الحروف والنقاط والشرطات والأقواس، مع الحفاظ على الأرقام فقط

 </div>

In [61]:
df['Phone_Number'] = df['Phone_Number'].str.replace(f'\D', '', regex=True)
df['Phone_Number']

<>:1: SyntaxWarning: invalid escape sequence '\D'
<>:1: SyntaxWarning: invalid escape sequence '\D'
C:\Users\Ayaz Taher\AppData\Local\Temp\ipykernel_34680\2657792002.py:1: SyntaxWarning: invalid escape sequence '\D'
  df['Phone_Number'] = df['Phone_Number'].str.replace(f'\D', '', regex=True)

1             3187003947
2             8319091619
4             2244925094
6        527514118787554
9                   <NA>
              ...
5037     170737728981578
5039          4597165051
5040      68770445010011
5041    1455262181068759
5042         19204471045
Name: Phone_Number, Length: 3324, dtype: object

<div dir="rtl" style="text-align: right;">
3.11 إزالة الامتدادات بعد x إذا وجدت

 </div>

In [62]:
df['Phone_Number'] = df['Phone_Number'].str.replace(r'x\d+$', '', regex=True)
df['Phone_Number']

1             3187003947
2             8319091619
4             2244925094
6        527514118787554
9                   <NA>
              ...
5037     170737728981578
5039          4597165051
5040      68770445010011
5041    1455262181068759
5042         19204471045
Name: Phone_Number, Length: 3324, dtype: object

<div dir="rtl" style="text-align: right;">

3.12 إزالة الفراغات الزائدة في البداية أو النهاية
 </div>

In [63]:
df['Phone_Number'] = df['Phone_Number'].str.strip()
df['Phone_Number']

1             3187003947
2             8319091619
4             2244925094
6        527514118787554
9                   <NA>
              ...
5037     170737728981578
5039          4597165051
5040      68770445010011
5041    1455262181068759
5042         19204471045
Name: Phone_Number, Length: 3324, dtype: object

<div dir="rtl" style="text-align: right;">

3.13 التعامل مع القيم الفارغة <NA>
 </div>

In [64]:
df['Phone_Number'] = df['Phone_Number'].fillna('Unknown')
df['Phone_Number']

1             3187003947
2             8319091619
4             2244925094
6        527514118787554
9                Unknown
              ...
5037     170737728981578
5039          4597165051
5040      68770445010011
5041    1455262181068759
5042         19204471045
Name: Phone_Number, Length: 3324, dtype: object

<div dir="rtl" style="text-align: right;">
3.14 قص أو التحقق من طول الرقم

 </div>

In [65]:
df['Phone_Number'] = df['Phone_Number'].where(df['Phone_Number'].str.len().between(10,15), 'Invalid')
df['Phone_Number']

1            3187003947
2            8319091619
4            2244925094
6       527514118787554
9               Invalid
             ...
5037    170737728981578
5039         4597165051
5040     68770445010011
5041            Invalid
5042        19204471045
Name: Phone_Number, Length: 3324, dtype: object

<div dir="rtl" style="text-align: right;">

4. هندسة المزايا, توليد او انشاء اعمدة او بيانات جديدة

 </div>

<div dir="rtl" style="text-align: right;">

4.1 تقسيم عمود الى عدم اعمدة بالاستناد على رمز محدد
 </div>

In [66]:
df.head(5)

,Customer_ID,First_Name,Last_Name,Gender,Age,Phone_Number,Address,Join_Date,Last_Purchase_Date,Category,...,Avg_Discount_Used,Total_Refund_Amount,Monthly_Spending_Estimate,Shipping_Distance_KM,Complaints_Count,Preferred_Contact_Time,Customer_Tier,Communication_Preference,Favorite_Product_Category,Special_Notes
1,f728b4fa-4248-4e3a-8a5d-2f346baa9455,Crystal,/Atkins,M,65.0,3187003947,"335 Justin Falls Apt. 281, NC, 44166",5/7/2021,3/25/2025,Beauty,...,-3.469217,6.153640,16.167151,-9.268747,-7.374091,Evening,Bronze,NaN,NaN,Long-Term
2,eb1167b3-67a9-4378-bc65-c1e582e2e662,Deborah,...Moore,F,18.0,8319091619,"19005 Young Divide, FL, 54121",3/3/2024,3/22/2025,Sports,...,9.471970,13.200408,4.778315,0.647364,0.999436,Afternoon,Bronze,Phone,NaN,VIP
4,e443df78-9558-467f-9ba9-1faf7a024204,Anna,/Garrett,M,21.0,2244925094,"5272 Krista Street, FL, 81468",6/7/2025,6/30/2025,Clothing,...,2.202235,-19.253180,-17.898067,5.589338,6.346641,Afternoon,Bronze,Email,Home,New Customer
6,1846d424-c17c-4279-a3c6-612f48268673,Colton,Goodwin__,,45.0,527514118787554,"12953 Livingston Port, AZ, 69706",12/30/2022,2/9/2025,Beauty,...,5.904719,-2.076232,400.000000,9.360077,16.319128,Afternoon,Platinum,NaN,NaN,Long-Term
9,259f4329-e6f4-490b-9a16-4106cf6a659e,John,Fuentes,M,68.0,Invalid,"881 Jacobs Lodge Suite 026, NC, 58467",7/8/2022,6/13/2025,Beauty,...,10.548937,3.023897,19.397687,-7.351723,0.506779,Morning,Bronze,NaN,Sports,New Customer

In [67]:
df[["Street_Address", "State","Zip_Code"]] = df["Address"].str.split(',', expand=True)
df.head(5)

,Customer_ID,First_Name,Last_Name,Gender,Age,Phone_Number,Address,Join_Date,Last_Purchase_Date,Category,...,Shipping_Distance_KM,Complaints_Count,Preferred_Contact_Time,Customer_Tier,Communication_Preference,Favorite_Product_Category,Special_Notes,Street_Address,State,Zip_Code
1,f728b4fa-4248-4e3a-8a5d-2f346baa9455,Crystal,/Atkins,M,65.0,3187003947,"335 Justin Falls Apt. 281, NC, 44166",5/7/2021,3/25/2025,Beauty,...,-9.268747,-7.374091,Evening,Bronze,NaN,NaN,Long-Term,335 Justin Falls Apt. 281,NC,44166
2,eb1167b3-67a9-4378-bc65-c1e582e2e662,Deborah,...Moore,F,18.0,8319091619,"19005 Young Divide, FL, 54121",3/3/2024,3/22/2025,Sports,...,0.647364,0.999436,Afternoon,Bronze,Phone,NaN,VIP,19005 Young Divide,FL,54121
4,e443df78-9558-467f-9ba9-1faf7a024204,Anna,/Garrett,M,21.0,2244925094,"5272 Krista Street, FL, 81468",6/7/2025,6/30/2025,Clothing,...,5.589338,6.346641,Afternoon,Bronze,Email,Home,New Customer,5272 Krista Street,FL,81468
6,1846d424-c17c-4279-a3c6-612f48268673,Colton,Goodwin__,,45.0,527514118787554,"12953 Livingston Port, AZ, 69706",12/30/2022,2/9/2025,Beauty,...,9.360077,16.319128,Afternoon,Platinum,NaN,NaN,Long-Term,12953 Livingston Port,AZ,69706
9,259f4329-e6f4-490b-9a16-4106cf6a659e,John,Fuentes,M,68.0,Invalid,"881 Jacobs Lodge Suite 026, NC, 58467",7/8/2022,6/13/2025,Beauty,...,-7.351723,0.506779,Morning,Bronze,NaN,Sports,New Customer,881 Jacobs Lodge Suite 026,NC,58467

<div dir="rtl" style="text-align: right;">

4.2 توحيد الفئات
 </div>

In [70]:
df.head(2)

,Customer_ID,First_Name,Last_Name,Gender,Age,Phone_Number,Address,Join_Date,Last_Purchase_Date,Category,...,Shipping_Distance_KM,Complaints_Count,Preferred_Contact_Time,Customer_Tier,Communication_Preference,Favorite_Product_Category,Special_Notes,Street_Address,State,Zip_Code
1,f728b4fa-4248-4e3a-8a5d-2f346baa9455,Crystal,/Atkins,M,65.0,3187003947,"335 Justin Falls Apt. 281, NC, 44166",5/7/2021,3/25/2025,Beauty,...,-9.268747,-7.374091,Evening,Bronze,NaN,NaN,Long-Term,335 Justin Falls Apt. 281,NC,44166
2,eb1167b3-67a9-4378-bc65-c1e582e2e662,Deborah,...Moore,F,18.0,8319091619,"19005 Young Divide, FL, 54121",3/3/2024,3/22/2025,Sports,...,0.647364,0.999436,Afternoon,Bronze,Phone,NaN,VIP,19005 Young Divide,FL,54121

In [75]:
df["Gender"] = df["Gender"].str.replace("M", "Male")
df["Gender"] = df["Gender"].str.replace("F", "Female")
df.head(20)

,Customer_ID,First_Name,Last_Name,Gender,Age,Phone_Number,Address,Join_Date,Last_Purchase_Date,Category,...,Shipping_Distance_KM,Complaints_Count,Preferred_Contact_Time,Customer_Tier,Communication_Preference,Favorite_Product_Category,Special_Notes,Street_Address,State,Zip_Code
1,f728b4fa-4248-4e3a-8a5d-2f346baa9455,Crystal,/Atkins,Malealeale,65.0,3187003947,"335 Justin Falls Apt. 281, NC, 44166",5/7/2021,3/25/2025,Beauty,...,-9.268747,-7.374091,Evening,Bronze,NaN,NaN,Long-Term,335 Justin Falls Apt. 281,NC,44166
2,eb1167b3-67a9-4378-bc65-c1e582e2e662,Deborah,...Moore,Femaleemaleemale,18.0,8319091619,"19005 Young Divide, FL, 54121",3/3/2024,3/22/2025,Sports,...,0.647364,0.999436,Afternoon,Bronze,Phone,NaN,VIP,19005 Young Divide,FL,54121
4,e443df78-9558-467f-9ba9-1faf7a024204,Anna,/Garrett,Malealeale,21.0,2244925094,"5272 Krista Street, FL, 81468",6/7/2025,6/30/2025,Clothing,...,5.589338,6.346641,Afternoon,Bronze,Email,Home,New Customer,5272 Krista Street,FL,81468
6,1846d424-c17c-4279-a3c6-612f48268673,Colton,Goodwin__,,45.0,527514118787554,"12953 Livingston Port, AZ, 69706",12/30/2022,2/9/2025,Beauty,...,9.360077,16.319128,Afternoon,Platinum,NaN,NaN,Long-Term,12953 Livingston Port,AZ,69706
10,12e0c8b2-bad6-40fb-9948-8dec4f65d4d9,Kayla,/Rivera,Malealeale,54.0,2656227640,"13185 Sweeney Loaf, AZ, 87160",5/1/2021,7/8/2025,Sports,...,7.696575,-16.844537,Afternoon,Bronze,SMS,Clothing,New Customer,13185 Sweeney Loaf,AZ,87160
11,5487ce1e-af19-422a-99b8-a714e61a441c,Daniel,/Davis,Malealeale,41.0,966822193275473,"740 Lisa Rapids Apt. 672, CA, 56584",4/26/2024,11/20/2025,Sports,...,-1.750882,7.836259,Afternoon,Bronze,NaN,Home,New Customer,740 Lisa Rapids Apt. 672,CA,56584
18,b5d32b16-6619-4cb1-9710-37d1b83e90ec,Randy,...Odonnell,Femaleemaleemaleemale,57.0,0016948322949,"675 Larry Trail Apt. 265, WA, 42147",7/3/2022,4/9/2025,Sports,...,7.076050,0.826773,Morning,Gold,Email,Home,Long-Term,675 Larry Trail Apt. 265,WA,42147
26,e005b860-51ef-4922-be43-c49e149818d1,Colleen,/Nunez,Malealealeale,26.0,12999186188251,"7147 Weber Union, FL, 25601",11/9/2021,11/11/2025,Sports,...,-12.249042,16.422026,Morning,Platinum,Phone,Home,VIP,7147 Weber Union,FL,25601
27,7d41e602-eece-428b-bf7b-118e820865d6,Erica,...Murphy,Malealeale,27.0,12996352867,"69962 Barry Vista, FL, 44665",2/15/2022,2/11/2025,Beauty,...,-7.002972,0.920345,Evening,Bronze,SMS,NaN,Long-Term,69962 Barry Vista,FL,44665
29,552f233a-8c25-466a-9ff3-9849b4e1357d,Andrew,Franco__,Femaleemaleemaleemale,69.0,4707522843,"71970 Kurt Trafficway, CA, 54456",11/15/2024,12/12/2024,Home,...,11.129243,5.941420,Morning,Bronze,NaN,Electronics,Long-Term,71970 Kurt Trafficway,CA,54456
30,3405095c-8a50-46c1-ac18-8efbd080e66e,Nicole,Perez,Malealealeale,34.0,2445513289069,"488 Hawkins Summit, WA, 81632",1/1/2022,2/18/2025,Clothing,...,-10.558188,0.198931,Morning,Silver,NaN,Beauty,Long-Term,488 Hawkins Summit,WA,81632
32,1775336d-71ea-4d05-89a3-e80e966e1277,Nicole,Lewis,Femaleemaleemaleemale,23.0,910971711785613,"9196 Linda Terrace, NC, 43035",9/26/2025,5/24/2025,Home,...,2.253831,0.936680,Morning,Silver,NaN,Electronics,VIP,9196 Linda Terrace,NC,43035
34,2f120554-4a53-48cc-bdfa-bc08935ddd72,Brandy,/Mullins,Malealeale,65.0,4058007778,"566 Robinson Path, FL, 27986",10/2/2025,11/22/2025,Home,...,-9.333576,10.190324,Morning,Gold,Email,Electronics,VIP,566 Robinson Path,FL,27986
39,148b2758-d7ab-4928-89e4-69e6ec62b2c8,Betty,Mora,Malealeale,67.0,4944017332848,"08950 Rogers Grove Apt. 322, NV, 86704",10/29/2022,7/6/2025,Sports,...,-3.945995,6.699155,Afternoon,Gold,NaN,Sports,New Customer,08950 Rogers Grove Apt. 322,NV,86704
40,d450fe4a-ec4f-417b-b306-d1a8e5eeac76,Mark,/Walker,Malealealeale,69.0,7793015108,"07113 Schmidt Rest Suite 657, NC, 13333",7/28/2022,10/26/2025,Sports,...,-2.446146,7.295269,Afternoon,Silver,SMS,Beauty,VIP,07113 Schmidt Rest Suite 657,NC,13333
42,85940927-468f-453d-864a-7a50b48d73f1,Samantha,...Calderon,Malealealeale,37.0,162366566938197,"506 Swanson Centers Suite 009, NC, 17018",12/1/2022,12/12/2024,Clothing,...,-0.683558,17.807925,Afternoon,Silver,NaN,Beauty,Long-Term,506 Swanson Centers Suite 009,NC,17018
44,d3447490-96fd-45d0-adf2-0806e5214606,Kevin,Bautista,,32.0,13808913074,"47761 Hooper Drive, WA, 69843",5/10/2021,4/2/2025,Electronics,...,-9.818887,-14.838772,Morning,Gold,Email,Home,Long-Term,47761 Hooper Drive,WA,69843
46,a425799a-a905-4750-be1e-a9c573581a81,David,Campbell,Femaleemaleemale,50.0,5674209349,"0845 Ferguson Loaf, WA, 74383",10/23/2025,2/12/2025,Sports,...,2.778626,16.937082,Morning,Silver,NaN,NaN,VIP,0845 Ferguson Loaf,WA,74383
47,fb82860d-eabc-48d0-b341-facdff0ac0f1,Andrew,...Barajas,,19.0,19982428413805,"9724 Brown Throughway Suite 504, CO, 76737",9/24/2025,7/14/2025,Home,...,-11.032491,15.086255,Morning,Platinum,Phone,Sports,Long-Term,9724 Brown Throughway Suite 504,CO,76737
49,964a870c-7c87-4b74-9d87-8f9f9cdf5a86,Angela,Everett,Femaleemaleemale,50.0,14924904762,"288 Larry Port Apt. 940, FL, 11150",6/30/2025,9/8/2025,Beauty,...,-23.925747,2.167359,Evening,Platinum,SMS,NaN,Long-Term,288 Larry Port Apt. 940,FL,11150

<div dir="rtl" style="text-align: right;">

4.3 حذف الصفوف بالاعتماد على شرط ضمن عمود او عدة اعمدة 
</div>

In [74]:
df = df[(df["Phone_Number"] != '') & (df["Phone_Number"] != 'Invalid')]
df.head(20)

,Customer_ID,First_Name,Last_Name,Gender,Age,Phone_Number,Address,Join_Date,Last_Purchase_Date,Category,...,Shipping_Distance_KM,Complaints_Count,Preferred_Contact_Time,Customer_Tier,Communication_Preference,Favorite_Product_Category,Special_Notes,Street_Address,State,Zip_Code
1,f728b4fa-4248-4e3a-8a5d-2f346baa9455,Crystal,/Atkins,Maleale,65.0,3187003947,"335 Justin Falls Apt. 281, NC, 44166",5/7/2021,3/25/2025,Beauty,...,-9.268747,-7.374091,Evening,Bronze,NaN,NaN,Long-Term,335 Justin Falls Apt. 281,NC,44166
2,eb1167b3-67a9-4378-bc65-c1e582e2e662,Deborah,...Moore,Femaleemale,18.0,8319091619,"19005 Young Divide, FL, 54121",3/3/2024,3/22/2025,Sports,...,0.647364,0.999436,Afternoon,Bronze,Phone,NaN,VIP,19005 Young Divide,FL,54121
4,e443df78-9558-467f-9ba9-1faf7a024204,Anna,/Garrett,Maleale,21.0,2244925094,"5272 Krista Street, FL, 81468",6/7/2025,6/30/2025,Clothing,...,5.589338,6.346641,Afternoon,Bronze,Email,Home,New Customer,5272 Krista Street,FL,81468
6,1846d424-c17c-4279-a3c6-612f48268673,Colton,Goodwin__,,45.0,527514118787554,"12953 Livingston Port, AZ, 69706",12/30/2022,2/9/2025,Beauty,...,9.360077,16.319128,Afternoon,Platinum,NaN,NaN,Long-Term,12953 Livingston Port,AZ,69706
10,12e0c8b2-bad6-40fb-9948-8dec4f65d4d9,Kayla,/Rivera,Maleale,54.0,2656227640,"13185 Sweeney Loaf, AZ, 87160",5/1/2021,7/8/2025,Sports,...,7.696575,-16.844537,Afternoon,Bronze,SMS,Clothing,New Customer,13185 Sweeney Loaf,AZ,87160
11,5487ce1e-af19-422a-99b8-a714e61a441c,Daniel,/Davis,Maleale,41.0,966822193275473,"740 Lisa Rapids Apt. 672, CA, 56584",4/26/2024,11/20/2025,Sports,...,-1.750882,7.836259,Afternoon,Bronze,NaN,Home,New Customer,740 Lisa Rapids Apt. 672,CA,56584
18,b5d32b16-6619-4cb1-9710-37d1b83e90ec,Randy,...Odonnell,Femaleemaleemale,57.0,0016948322949,"675 Larry Trail Apt. 265, WA, 42147",7/3/2022,4/9/2025,Sports,...,7.076050,0.826773,Morning,Gold,Email,Home,Long-Term,675 Larry Trail Apt. 265,WA,42147
26,e005b860-51ef-4922-be43-c49e149818d1,Colleen,/Nunez,Malealeale,26.0,12999186188251,"7147 Weber Union, FL, 25601",11/9/2021,11/11/2025,Sports,...,-12.249042,16.422026,Morning,Platinum,Phone,Home,VIP,7147 Weber Union,FL,25601
27,7d41e602-eece-428b-bf7b-118e820865d6,Erica,...Murphy,Maleale,27.0,12996352867,"69962 Barry Vista, FL, 44665",2/15/2022,2/11/2025,Beauty,...,-7.002972,0.920345,Evening,Bronze,SMS,NaN,Long-Term,69962 Barry Vista,FL,44665
29,552f233a-8c25-466a-9ff3-9849b4e1357d,Andrew,Franco__,Femaleemaleemale,69.0,4707522843,"71970 Kurt Trafficway, CA, 54456",11/15/2024,12/12/2024,Home,...,11.129243,5.941420,Morning,Bronze,NaN,Electronics,Long-Term,71970 Kurt Trafficway,CA,54456
30,3405095c-8a50-46c1-ac18-8efbd080e66e,Nicole,Perez,Malealeale,34.0,2445513289069,"488 Hawkins Summit, WA, 81632",1/1/2022,2/18/2025,Clothing,...,-10.558188,0.198931,Morning,Silver,NaN,Beauty,Long-Term,488 Hawkins Summit,WA,81632
32,1775336d-71ea-4d05-89a3-e80e966e1277,Nicole,Lewis,Femaleemaleemale,23.0,910971711785613,"9196 Linda Terrace, NC, 43035",9/26/2025,5/24/2025,Home,...,2.253831,0.936680,Morning,Silver,NaN,Electronics,VIP,9196 Linda Terrace,NC,43035
34,2f120554-4a53-48cc-bdfa-bc08935ddd72,Brandy,/Mullins,Maleale,65.0,4058007778,"566 Robinson Path, FL, 27986",10/2/2025,11/22/2025,Home,...,-9.333576,10.190324,Morning,Gold,Email,Electronics,VIP,566 Robinson Path,FL,27986
39,148b2758-d7ab-4928-89e4-69e6ec62b2c8,Betty,Mora,Maleale,67.0,4944017332848,"08950 Rogers Grove Apt. 322, NV, 86704",10/29/2022,7/6/2025,Sports,...,-3.945995,6.699155,Afternoon,Gold,NaN,Sports,New Customer,08950 Rogers Grove Apt. 322,NV,86704
40,d450fe4a-ec4f-417b-b306-d1a8e5eeac76,Mark,/Walker,Malealeale,69.0,7793015108,"07113 Schmidt Rest Suite 657, NC, 13333",7/28/2022,10/26/2025,Sports,...,-2.446146,7.295269,Afternoon,Silver,SMS,Beauty,VIP,07113 Schmidt Rest Suite 657,NC,13333
42,85940927-468f-453d-864a-7a50b48d73f1,Samantha,...Calderon,Malealeale,37.0,162366566938197,"506 Swanson Centers Suite 009, NC, 17018",12/1/2022,12/12/2024,Clothing,...,-0.683558,17.807925,Afternoon,Silver,NaN,Beauty,Long-Term,506 Swanson Centers Suite 009,NC,17018
44,d3447490-96fd-45d0-adf2-0806e5214606,Kevin,Bautista,,32.0,13808913074,"47761 Hooper Drive, WA, 69843",5/10/2021,4/2/2025,Electronics,...,-9.818887,-14.838772,Morning,Gold,Email,Home,Long-Term,47761 Hooper Drive,WA,69843
46,a425799a-a905-4750-be1e-a9c573581a81,David,Campbell,Femaleemale,50.0,5674209349,"0845 Ferguson Loaf, WA, 74383",10/23/2025,2/12/2025,Sports,...,2.778626,16.937082,Morning,Silver,NaN,NaN,VIP,0845 Ferguson Loaf,WA,74383
47,fb82860d-eabc-48d0-b341-facdff0ac0f1,Andrew,...Barajas,,19.0,19982428413805,"9724 Brown Throughway Suite 504, CO, 76737",9/24/2025,7/14/2025,Home,...,-11.032491,15.086255,Morning,Platinum,Phone,Sports,Long-Term,9724 Brown Throughway Suite 504,CO,76737
49,964a870c-7c87-4b74-9d87-8f9f9cdf5a86,Angela,Everett,Femaleemale,50.0,14924904762,"288 Larry Port Apt. 940, FL, 11150",6/30/2025,9/8/2025,Beauty,...,-23.925747,2.167359,Evening,Platinum,SMS,NaN,Long-Term,288 Larry Port Apt. 940,FL,11150

<div dir="rtl" style="text-align: right;">

اعادة الفهرسة</div>

In [78]:
df = df.reset_index(drop=True)
df

,Customer_ID,First_Name,Last_Name,Gender,Age,Phone_Number,Address,Join_Date,Last_Purchase_Date,Category,...,Shipping_Distance_KM,Complaints_Count,Preferred_Contact_Time,Customer_Tier,Communication_Preference,Favorite_Product_Category,Special_Notes,Street_Address,State,Zip_Code
0,f728b4fa-4248-4e3a-8a5d-2f346baa9455,Crystal,/Atkins,Malealeale,65.0,3187003947,"335 Justin Falls Apt. 281, NC, 44166",5/7/2021,3/25/2025,Beauty,...,-9.268747,-7.374091,Evening,Bronze,NaN,NaN,Long-Term,335 Justin Falls Apt. 281,NC,44166
1,eb1167b3-67a9-4378-bc65-c1e582e2e662,Deborah,...Moore,Femaleemaleemale,18.0,8319091619,"19005 Young Divide, FL, 54121",3/3/2024,3/22/2025,Sports,...,0.647364,0.999436,Afternoon,Bronze,Phone,NaN,VIP,19005 Young Divide,FL,54121
2,e443df78-9558-467f-9ba9-1faf7a024204,Anna,/Garrett,Malealeale,21.0,2244925094,"5272 Krista Street, FL, 81468",6/7/2025,6/30/2025,Clothing,...,5.589338,6.346641,Afternoon,Bronze,Email,Home,New Customer,5272 Krista Street,FL,81468
3,1846d424-c17c-4279-a3c6-612f48268673,Colton,Goodwin__,,45.0,527514118787554,"12953 Livingston Port, AZ, 69706",12/30/2022,2/9/2025,Beauty,...,9.360077,16.319128,Afternoon,Platinum,NaN,NaN,Long-Term,12953 Livingston Port,AZ,69706
4,12e0c8b2-bad6-40fb-9948-8dec4f65d4d9,Kayla,/Rivera,Malealeale,54.0,2656227640,"13185 Sweeney Loaf, AZ, 87160",5/1/2021,7/8/2025,Sports,...,7.696575,-16.844537,Afternoon,Bronze,SMS,Clothing,New Customer,13185 Sweeney Loaf,AZ,87160
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1359,7c23bbfc-0490-442f-9b5b-f01f3d75489a,Peter,Martin__,Femaleemaleemaleemale,26.0,2818539740,"4557 Deborah Common Suite 103, CO, 71972",3/8/2025,8/20/2025,Beauty,...,-2.609829,-16.121219,Morning,Bronze,Email,Electronics,Long-Term,4557 Deborah Common Suite 103,CO,71972
1360,defa7864-15ac-45c3-a217-cf253be95767,John,/Hardy,Malealealeale,59.0,170737728981578,"90555 Justin Views Suite 743, NY, 20361",6/13/2022,3/11/2025,Automotive,...,14.823340,0.920345,Morning,Gold,Email,Clothing,Long-Term,90555 Justin Views Suite 743,NY,20361
1361,1e8e2d52-2ab9-4185-9af0-ed2850bea76b,Sean,...Espinoza,Femaleemaleemaleemale,35.0,4597165051,"937 Devin Flats, NV, 18768",3/18/2024,4/5/2025,Clothing,...,10.851671,-1.599371,Morning,Bronze,Phone,Home,New Customer,937 Devin Flats,NV,18768
1362,9be6a1c7-3882-4ff2-a569-30b895b30690,Gabrielle,/Walton,Malealeale,68.0,68770445010011,"9316 Martinez Ways, NC, 04007",7/14/2025,12/22/2024,Clothing,...,-2.172965,-23.922515,NaN,Platinum,Phone,Sports,Long-Term,9316 Martinez Ways,NC,04007
1363,3c669aa5-50bb-41c7-b01c-ccc7bb87c961,Darlene,Olson,Malealeale,52.0,19204471045,"95410 Ellen Road Apt. 972, CA, 76785",6/17/2022,3/20/2025,Home,...,-12.749877,0.920345,NaN,Platinum,Email,Home,Long-Term,95410 Ellen Road Apt. 972,CA,76785