

<div dir="rtl" style="text-align: right;">

## Pandas Course الدرس الرابع 4
 </div>


<div dir="rtl" style="text-align: right;">

## Filtering and ordering التصفية والترتيب
 </div>


<div dir="rtl" style="text-align: right;">
استيراد المكتبة

 </div>

In [8]:
import pandas as pd


<div dir="rtl" style="text-align: right;">
0. قراءة الملف


 </div>

In [9]:
df = pd.read_csv(r"D:\Pandas\Pandas_Course\world_population.csv")


<div dir="rtl" style="text-align: right;">
1. عرض البيانات

 </div>

In [10]:
df

,Rank,CCA3,Country,Capital,Continent,Average,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (km²),Density (per km²),Growth Rate,World Population Percentage
0,36,AFG,Afghanistan,Kabul,Asia,2.444019e+07,41128771.0,38972230.0,33753499.0,28189672.0,19542982.0,10694796.0,12486631.0,10752971.0,652230.0,63.0587,1.0257,0.52
1,138,ALB,Albania,Tirana,Europe,2.906065e+06,2842321.0,2866849.0,2882481.0,2913399.0,3182021.0,3295066.0,2941651.0,2324731.0,28748.0,98.8702,0.9957,0.04
2,34,DZA,Algeria,Algiers,Africa,3.157280e+07,44903225.0,43451666.0,39543154.0,35856344.0,30774621.0,25518074.0,18739378.0,13795915.0,2381741.0,18.8531,1.0164,0.56
3,213,ASM,American Samoa,Pago Pago,Oceania,4.533600e+04,44273.0,46189.0,51368.0,54849.0,58230.0,47818.0,32886.0,27075.0,199.0,222.4774,0.9831,0.00
4,203,AND,Andorra,Andorra la Vella,Europe,5.949075e+04,79824.0,77700.0,71746.0,71519.0,66097.0,53569.0,35611.0,19860.0,468.0,170.5641,1.0100,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
229,226,WLF,Wallis and Futuna,Mata-Utu,Oceania,1.217750e+04,11572.0,11655.0,12182.0,13142.0,14723.0,13454.0,11315.0,9377.0,142.0,81.4930,0.9953,0.00
230,172,ESH,Western Sahara,El Aaiún,Africa,3.349005e+05,575986.0,556048.0,491824.0,413296.0,270375.0,178529.0,116775.0,76371.0,266000.0,2.1654,1.0184,0.01
231,46,YEM,Yemen,Sanaa,Asia,2.091169e+07,33696614.0,32284046.0,28516545.0,24743946.0,18628700.0,13375121.0,9204938.0,6843607.0,527968.0,63.8232,1.0217,0.42
232,63,ZMB,Zambia,Lusaka,Africa,1.147387e+07,20017675.0,18927715.0,NaN,13792086.0,9891136.0,7686401.0,5720438.0,4281671.0,752612.0,26.5976,1.0280,0.25
233,74,ZWE,Zimbabwe,Harare,Africa,1.164829e+07,16320537.0,15669666.0,14154937.0,12839771.0,11834676.0,10113893.0,7049926.0,5202918.0,390757.0,41.7665,1.0204,0.20


<div dir="rtl" style="text-align: right;">
2. تصفية الصفوف (Rows) بحسب شرط معين
 </div>

In [11]:
df[df["Rank"] <=10]

,Rank,CCA3,Country,Capital,Continent,Average,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (km²),Density (per km²),Growth Rate,World Population Percentage
16,8,BGD,Bangladesh,Dhaka,Asia,1.290801e+08,1.711864e+08,1.674210e+08,1.578300e+08,1.483911e+08,1.291933e+08,1.071477e+08,83929765.0,67541860.0,147570.0,1160.0350,1.0108,2.15
27,7,BRA,Brazil,Brasilia,South America,1.719112e+08,2.153135e+08,2.131963e+08,2.051882e+08,1.963535e+08,1.758737e+08,1.507064e+08,122288383.0,96369875.0,8515767.0,25.2841,1.0046,2.70
41,1,CHN,China,Beijing,Asia,1.226929e+09,1.425887e+09,1.424930e+09,1.393715e+09,1.348191e+09,1.264099e+09,1.153704e+09,982372466.0,822534450.0,9706961.0,146.8933,1.0000,17.88
92,2,IND,India,New Delhi,Asia,1.165696e+09,1.417173e+09,1.396387e+09,1.322867e+09,1.240614e+09,1.059634e+09,NaN,NaN,557501301.0,3287590.0,431.0675,1.0068,17.77
93,4,IDN,Indonesia,Jakarta,Asia,2.137632e+08,2.755013e+08,2.718580e+08,2.590920e+08,2.440162e+08,2.140724e+08,1.821599e+08,148177096.0,115228394.0,1904569.0,144.6529,1.0064,3.45
131,10,MEX,Mexico,Mexico City,North America,9.797164e+07,1.275041e+08,1.259983e+08,1.201499e+08,1.125324e+08,9.787344e+07,8.172043e+07,67705186.0,50289306.0,1964375.0,64.9082,1.0063,1.60
149,6,NGA,Nigeria,Abuja,Africa,1.398005e+08,2.185412e+08,2.083274e+08,1.839958e+08,1.609529e+08,1.228520e+08,9.521426e+07,72951439.0,55569264.0,923768.0,236.5759,1.0241,2.74
156,5,PAK,Pakistan,Islamabad,Asia,1.597680e+08,2.358249e+08,2.271967e+08,2.109693e+08,1.944545e+08,1.543699e+08,1.154141e+08,80624057.0,59290872.0,881912.0,267.4018,1.0191,2.96
171,9,RUS,Russia,Moscow,Europe,1.426803e+08,1.447133e+08,1.456173e+08,1.446684e+08,1.432426e+08,1.468448e+08,1.480057e+08,138257420.0,130093010.0,17098242.0,8.4636,0.9973,1.81
221,3,USA,United States,"Washington, D.C.",North America,2.829966e+08,3.382899e+08,3.359420e+08,3.246078e+08,3.111828e+08,2.823986e+08,2.480837e+08,223140018.0,200328340.0,9372610.0,36.0935,1.0038,4.24


<div dir="rtl" style="text-align: right;">
3. تصفية الصفوف (Rows) بحسب  تصفية بشرطين معاً
 </div>

In [13]:
df_filter = df[(df['Continent'] == 'Asia') & (df['2022 Population'] > 50_000_000)]
df_filter

,Rank,CCA3,Country,Capital,Continent,Average,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (km²),Density (per km²),Growth Rate,World Population Percentage
16,8,BGD,Bangladesh,Dhaka,Asia,1.290801e+08,1.711864e+08,1.674210e+08,1.578300e+08,1.483911e+08,1.291933e+08,1.071477e+08,83929765.0,67541860.0,147570.0,1160.0350,1.0108,2.15
41,1,CHN,China,Beijing,Asia,1.226929e+09,1.425887e+09,1.424930e+09,1.393715e+09,1.348191e+09,1.264099e+09,1.153704e+09,982372466.0,822534450.0,9706961.0,146.8933,1.0000,17.88
92,2,IND,India,New Delhi,Asia,1.165696e+09,1.417173e+09,1.396387e+09,1.322867e+09,1.240614e+09,1.059634e+09,NaN,NaN,557501301.0,3287590.0,431.0675,1.0068,17.77
93,4,IDN,Indonesia,Jakarta,Asia,2.137632e+08,2.755013e+08,2.718580e+08,2.590920e+08,2.440162e+08,2.140724e+08,1.821599e+08,148177096.0,115228394.0,1904569.0,144.6529,1.0064,3.45
94,17,IRN,Iran,Tehran,Asia,6.516423e+07,8.855057e+07,8.729019e+07,8.179084e+07,7.537386e+07,6.554438e+07,5.579363e+07,38520664.0,28449705.0,1648195.0,53.7258,1.0071,1.11
102,11,JPN,Japan,Tokyo,Asia,1.222605e+08,1.239517e+08,1.252448e+08,1.272509e+08,1.281054e+08,1.268039e+08,1.236863e+08,117624196.0,105416839.0,377930.0,327.9753,0.9947,1.55
140,26,MMR,Myanmar,Nay Pyi Taw,Asia,4.435815e+07,5.417931e+07,5.342320e+07,5.148395e+07,4.939099e+07,4.553833e+07,4.009955e+07,33465781.0,27284112.0,676578.0,80.0784,1.0071,0.68
156,5,PAK,Pakistan,Islamabad,Asia,1.597680e+08,2.358249e+08,2.271967e+08,2.109693e+08,1.944545e+08,1.543699e+08,1.154141e+08,80624057.0,59290872.0,881912.0,267.4018,1.0191,2.96
163,13,PHL,Philippines,Manila,Asia,8.134879e+07,1.155590e+08,1.121910e+08,1.030314e+08,9.463670e+07,7.795822e+07,6.155890e+07,48419546.0,37435586.0,342353.0,337.5434,1.0147,1.45
194,29,KOR,South Korea,Seoul,Asia,4.564353e+07,5.181581e+07,5.184469e+07,5.099440e+07,4.881304e+07,4.678859e+07,4.412004e+07,38170501.0,32601143.0,100210.0,517.0722,0.9997,0.65
206,20,THA,Thailand,Bangkok,Asia,6.368148e+07,7.169703e+07,7.147566e+07,7.029440e+07,6.827049e+07,6.306660e+07,5.522841e+07,45737753.0,NaN,513120.0,139.7276,1.0013,0.90
213,18,TUR,Turkey,Ankara,Asia,6.504824e+07,8.534124e+07,8.413543e+07,7.964618e+07,7.319534e+07,6.411355e+07,5.432414e+07,44089069.0,35540990.0,783562.0,108.9145,1.0067,1.07
228,16,VNM,Vietnam,Hanoi,Asia,7.690610e+07,9.818686e+07,9.664868e+07,9.219140e+07,8.741101e+07,7.900114e+07,6.691261e+07,52968270.0,41928849.0,331212.0,296.4472,1.0074,1.23


<div dir="rtl" style="text-align: right;">

4. التصفية باستخدام OR

 </div>

In [21]:
df_or = df[(df['Continent'] == 'Asia') | (df['Continent'] == 'Africa')]
df_or

,Rank,CCA3,Country,Capital,Continent,Average,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (km²),Density (per km²),Growth Rate,World Population Percentage
0,36,AFG,Afghanistan,Kabul,Asia,2.444019e+07,41128771.0,38972230.0,33753499.0,28189672.0,19542982.0,10694796.0,12486631.0,10752971.0,652230.0,63.0587,1.0257,0.52
2,34,DZA,Algeria,Algiers,Africa,3.157280e+07,44903225.0,43451666.0,39543154.0,35856344.0,30774621.0,25518074.0,18739378.0,13795915.0,2381741.0,18.8531,1.0164,0.56
5,42,AGO,Angola,Luanda,Africa,2.038648e+07,35588987.0,33428485.0,28127721.0,23364185.0,16394062.0,11828638.0,8330047.0,6029700.0,1246700.0,28.5466,1.0315,0.45
9,140,ARM,Armenia,Yerevan,Asia,2.975691e+06,2780469.0,2805608.0,2878595.0,2946293.0,3168523.0,3556539.0,3135123.0,2534377.0,29743.0,93.4831,0.9962,0.03
13,91,AZE,Azerbaijan,Baku,Asia,8.126472e+06,10358074.0,NaN,9863480.0,9237202.0,8190337.0,7427836.0,6383060.0,5425317.0,86600.0,119.6082,1.0044,0.13
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
228,16,VNM,Vietnam,Hanoi,Asia,7.690610e+07,98186856.0,96648685.0,92191398.0,87411012.0,79001142.0,66912613.0,52968270.0,41928849.0,331212.0,296.4472,1.0074,1.23
230,172,ESH,Western Sahara,El Aaiún,Africa,3.349005e+05,575986.0,556048.0,491824.0,413296.0,270375.0,178529.0,116775.0,76371.0,266000.0,2.1654,1.0184,0.01
231,46,YEM,Yemen,Sanaa,Asia,2.091169e+07,33696614.0,32284046.0,28516545.0,24743946.0,18628700.0,13375121.0,9204938.0,6843607.0,527968.0,63.8232,1.0217,0.42
232,63,ZMB,Zambia,Lusaka,Africa,1.147387e+07,20017675.0,18927715.0,NaN,13792086.0,9891136.0,7686401.0,5720438.0,4281671.0,752612.0,26.5976,1.0280,0.25
233,74,ZWE,Zimbabwe,Harare,Africa,1.164829e+07,16320537.0,15669666.0,14154937.0,12839771.0,11834676.0,10113893.0,7049926.0,5202918.0,390757.0,41.7665,1.0204,0.20


<div dir="rtl" style="text-align: right;">

5. التصفية بالنفي
 </div>

In [25]:
df_not = df[~df['Continent'].isin(['Asia','Africa'])]
df_not

,Rank,CCA3,Country,Capital,Continent,Average,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (km²),Density (per km²),Growth Rate,World Population Percentage
1,138,ALB,Albania,Tirana,Europe,2.906065e+06,2842321.0,2866849.0,2882481.0,2913399.0,3182021.0,3295066.0,2941651.0,2324731.0,28748.0,98.8702,0.9957,0.04
3,213,ASM,American Samoa,Pago Pago,Oceania,4.533600e+04,44273.0,46189.0,51368.0,54849.0,58230.0,47818.0,32886.0,27075.0,199.0,222.4774,0.9831,0.00
4,203,AND,Andorra,Andorra la Vella,Europe,5.949075e+04,79824.0,77700.0,71746.0,71519.0,66097.0,53569.0,35611.0,19860.0,468.0,170.5641,1.0100,0.00
6,224,AIA,Anguilla,The Valley,North America,1.141812e+04,15857.0,15585.0,14525.0,13172.0,11047.0,8316.0,6560.0,6283.0,91.0,174.2527,1.0066,0.00
7,201,ATG,Antigua and Barbuda,Saint John’s,North America,7.873125e+04,93763.0,92664.0,89941.0,85695.0,75055.0,63328.0,64888.0,64516.0,442.0,212.1335,1.0058,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
223,133,URY,Uruguay,Montevideo,South America,3.220075e+06,3422794.0,3429086.0,3402818.0,3352651.0,3292224.0,3117012.0,2953750.0,2790265.0,181034.0,18.9069,0.9990,0.04
225,181,VUT,Vanuatu,Port-Vila,Oceania,2.135559e+05,326740.0,311685.0,276438.0,245453.0,192074.0,150882.0,118156.0,87019.0,12189.0,26.8061,1.0238,0.00
226,234,VAT,Vatican City,Vatican City,Europe,6.282500e+02,510.0,520.0,564.0,596.0,651.0,700.0,733.0,752.0,1.0,510.0000,0.9980,0.00
227,51,VEN,Venezuela,Caracas,South America,2.319334e+07,28301696.0,28490453.0,30529716.0,28715022.0,NaN,19750579.0,15210443.0,11355475.0,NaN,30.8820,1.0036,0.35
229,226,WLF,Wallis and Futuna,Mata-Utu,Oceania,1.217750e+04,11572.0,11655.0,12182.0,13142.0,14723.0,13454.0,11315.0,9377.0,142.0,81.4930,0.9953,0.00


<div dir="rtl" style="text-align: right;">
6. تصفية الصفوف (Rows) بحسب قيم محددة 
 </div>

In [26]:
specific_countries = ['Bangladesh','Brazil']

df[df['Country'].isin(specific_countries)]

,Rank,CCA3,Country,Capital,Continent,Average,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (km²),Density (per km²),Growth Rate,World Population Percentage
16,8,BGD,Bangladesh,Dhaka,Asia,129080133.1,171186372.0,167420951.0,157830000.0,148391139.0,129193327.0,107147651.0,83929765.0,67541860.0,147570.0,1160.0350,1.0108,2.15
27,7,BRA,Brazil,Brasilia,South America,171911240.4,215313498.0,213196304.0,205188205.0,196353492.0,175873720.0,150706446.0,122288383.0,96369875.0,8515767.0,25.2841,1.0046,2.70


<div dir="rtl" style="text-align: right;">
7. فلترة الأسطر بحسب البحث عن قيمة معينة داخل عمود معين
</div>

In [27]:
df[df['Country'].str.contains('United')]

,Rank,CCA3,Country,Capital,Continent,Average,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (km²),Density (per km²),Growth Rate,World Population Percentage
219,97,ARE,United Arab Emirates,Abu Dhabi,Asia,5326838.0,9441129.0,9287289.0,8916899.0,8481771.0,3275333.0,1900151.0,1014048.0,298084.0,83600.0,112.9322,1.0081,0.12
220,21,GBR,United Kingdom,London,Europe,61323724.0,67508936.0,67059474.0,65224364.0,62760039.0,58850043.0,57210442.0,56326328.0,55650166.0,242900.0,277.9289,1.0034,0.85
221,3,USA,United States,"Washington, D.C.",North America,282996640.6,338289857.0,335942003.0,324607776.0,311182845.0,282398554.0,248083732.0,223140018.0,200328340.0,9372610.0,36.0935,1.0038,4.24
222,200,VIR,United States Virgin Islands,Charlotte Amalie,North America,97226.0,99465.0,100442.0,102803.0,106142.0,108185.0,100685.0,96640.0,63446.0,347.0,286.6427,0.9937,0.00


<div dir="rtl" style="text-align: right;">
تعديل الفهرسة</div>

In [28]:
df2 = df.set_index('Country')
df2

,Rank,CCA3,Capital,Continent,Average,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (km²),Density (per km²),Growth Rate,World Population Percentage
Country,,,,,,,,,,,,,,,,,
Afghanistan,36,AFG,Kabul,Asia,2.444019e+07,41128771.0,38972230.0,33753499.0,28189672.0,19542982.0,10694796.0,12486631.0,10752971.0,652230.0,63.0587,1.0257,0.52
Albania,138,ALB,Tirana,Europe,2.906065e+06,2842321.0,2866849.0,2882481.0,2913399.0,3182021.0,3295066.0,2941651.0,2324731.0,28748.0,98.8702,0.9957,0.04
Algeria,34,DZA,Algiers,Africa,3.157280e+07,44903225.0,43451666.0,39543154.0,35856344.0,30774621.0,25518074.0,18739378.0,13795915.0,2381741.0,18.8531,1.0164,0.56
American Samoa,213,ASM,Pago Pago,Oceania,4.533600e+04,44273.0,46189.0,51368.0,54849.0,58230.0,47818.0,32886.0,27075.0,199.0,222.4774,0.9831,0.00
Andorra,203,AND,Andorra la Vella,Europe,5.949075e+04,79824.0,77700.0,71746.0,71519.0,66097.0,53569.0,35611.0,19860.0,468.0,170.5641,1.0100,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Wallis and Futuna,226,WLF,Mata-Utu,Oceania,1.217750e+04,11572.0,11655.0,12182.0,13142.0,14723.0,13454.0,11315.0,9377.0,142.0,81.4930,0.9953,0.00
Western Sahara,172,ESH,El Aaiún,Africa,3.349005e+05,575986.0,556048.0,491824.0,413296.0,270375.0,178529.0,116775.0,76371.0,266000.0,2.1654,1.0184,0.01
Yemen,46,YEM,Sanaa,Asia,2.091169e+07,33696614.0,32284046.0,28516545.0,24743946.0,18628700.0,13375121.0,9204938.0,6843607.0,527968.0,63.8232,1.0217,0.42
Zambia,63,ZMB,Lusaka,Africa,1.147387e+07,20017675.0,18927715.0,NaN,13792086.0,9891136.0,7686401.0,5720438.0,4281671.0,752612.0,26.5976,1.0280,0.25
Zimbabwe,74,ZWE,Harare,Africa,1.164829e+07,16320537.0,15669666.0,14154937.0,12839771.0,11834676.0,10113893.0,7049926.0,5202918.0,390757.0,41.7665,1.0204,0.20


<div dir="rtl" style="text-align: right;">
8. تصفية الأعمدة واختيار عمودين فقط لإظهارهما
</div>

In [29]:
df2.filter(items = ['Continent', 'CCA3'], axis=1)

                  Continent CCA3
Country
Afghanistan            Asia  AFG
Albania              Europe  ALB
Algeria              Africa  DZA
American Samoa      Oceania  ASM
Andorra              Europe  AND
...                     ...  ...
Wallis and Futuna   Oceania  WLF
Western Sahara       Africa  ESH
Yemen                  Asia  YEM
Zambia               Africa  ZMB
Zimbabwe             Africa  ZWE

[234 rows x 2 columns]


<div dir="rtl" style="text-align: right;">
9. تصفية الأسطر  واختيار قيمة معينة (دولة) فقط لإظهارها
</div>

In [30]:
df2.filter(items=['Zimbabwe'], axis=0)

,Rank,CCA3,Capital,Continent,Average,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (km²),Density (per km²),Growth Rate,World Population Percentage
Zimbabwe,74,ZWE,Harare,Africa,11648290.5,16320537.0,15669666.0,14154937.0,12839771.0,11834676.0,10113893.0,7049926.0,5202918.0,390757.0,41.7665,1.0204,0.2


<div dir="rtl" style="text-align: right;">

10. تصفية الصفوف بالبحث عن قيمة محددة في عمود الفهرسة (الذي هو عمود الدولة)

</div>

In [31]:
df2.filter(like ='United', axis=0)

,Rank,CCA3,Capital,Continent,Average,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (km²),Density (per km²),Growth Rate,World Population Percentage
Country,,,,,,,,,,,,,,,,,
United Arab Emirates,97,ARE,Abu Dhabi,Asia,5326838.0,9441129.0,9287289.0,8916899.0,8481771.0,3275333.0,1900151.0,1014048.0,298084.0,83600.0,112.9322,1.0081,0.12
United Kingdom,21,GBR,London,Europe,61323724.0,67508936.0,67059474.0,65224364.0,62760039.0,58850043.0,57210442.0,56326328.0,55650166.0,242900.0,277.9289,1.0034,0.85
United States,3,USA,"Washington, D.C.",North America,282996640.6,338289857.0,335942003.0,324607776.0,311182845.0,282398554.0,248083732.0,223140018.0,200328340.0,9372610.0,36.0935,1.0038,4.24
United States Virgin Islands,200,VIR,Charlotte Amalie,North America,97226.0,99465.0,100442.0,102803.0,106142.0,108185.0,100685.0,96640.0,63446.0,347.0,286.6427,0.9937,0.00


<div dir="rtl" style="text-align: right;">

11. الوصول المباشر لبيانات وفق قيمة موجودة ضمن عمود الفهرسة (الذي هو عمود الدولة)
</div>

In [32]:
df2.loc['United States']

Rank                                          3
CCA3                                        USA
Capital                        Washington, D.C.
Continent                         North America
Average                             282996640.6
2022 Population                     338289857.0
2020 Population                     335942003.0
2015 Population                     324607776.0
2010 Population                     311182845.0
2000 Population                     282398554.0
1990 Population                     248083732.0
1980 Population                     223140018.0
1970 Population                     200328340.0
Area (km²)                            9372610.0
Density (per km²)                       36.0935
Growth Rate                              1.0038
World Population Percentage                4.24
Name: United States, dtype: object


<div dir="rtl" style="text-align: right;">

12. الوصول المباشر لبيانات وفق رقم الصف عمود
</div>

In [33]:
df2.iloc[3]

Rank                                 213
CCA3                                 ASM
Capital                        Pago Pago
Continent                        Oceania
Average                          45336.0
2022 Population                  44273.0
2020 Population                  46189.0
2015 Population                  51368.0
2010 Population                  54849.0
2000 Population                  58230.0
1990 Population                  47818.0
1980 Population                  32886.0
1970 Population                  27075.0
Area (km²)                         199.0
Density (per km²)               222.4774
Growth Rate                       0.9831
World Population Percentage          0.0
Name: American Samoa, dtype: object


<div dir="rtl" style="text-align: right;">

13. تصفية الصفوف وفق شرط معين و ترتيب تصاعدي للبيانات

</div>

In [34]:
df_filtered= df[df['Rank'] < 10].sort_values(by=['Continent', 'Country'], ascending=[False,True])
df_filtered

,Rank,CCA3,Country,Capital,Continent,Average,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (km²),Density (per km²),Growth Rate,World Population Percentage
27,7,BRA,Brazil,Brasilia,South America,1.719112e+08,2.153135e+08,2.131963e+08,2.051882e+08,1.963535e+08,1.758737e+08,1.507064e+08,122288383.0,96369875.0,8515767.0,25.2841,1.0046,2.70
221,3,USA,United States,"Washington, D.C.",North America,2.829966e+08,3.382899e+08,3.359420e+08,3.246078e+08,3.111828e+08,2.823986e+08,2.480837e+08,223140018.0,200328340.0,9372610.0,36.0935,1.0038,4.24
171,9,RUS,Russia,Moscow,Europe,1.426803e+08,1.447133e+08,1.456173e+08,1.446684e+08,1.432426e+08,1.468448e+08,1.480057e+08,138257420.0,130093010.0,17098242.0,8.4636,0.9973,1.81
16,8,BGD,Bangladesh,Dhaka,Asia,1.290801e+08,1.711864e+08,1.674210e+08,1.578300e+08,1.483911e+08,1.291933e+08,1.071477e+08,83929765.0,67541860.0,147570.0,1160.0350,1.0108,2.15
41,1,CHN,China,Beijing,Asia,1.226929e+09,1.425887e+09,1.424930e+09,1.393715e+09,1.348191e+09,1.264099e+09,1.153704e+09,982372466.0,822534450.0,9706961.0,146.8933,1.0000,17.88
92,2,IND,India,New Delhi,Asia,1.165696e+09,1.417173e+09,1.396387e+09,1.322867e+09,1.240614e+09,1.059634e+09,NaN,NaN,557501301.0,3287590.0,431.0675,1.0068,17.77
93,4,IDN,Indonesia,Jakarta,Asia,2.137632e+08,2.755013e+08,2.718580e+08,2.590920e+08,2.440162e+08,2.140724e+08,1.821599e+08,148177096.0,115228394.0,1904569.0,144.6529,1.0064,3.45
156,5,PAK,Pakistan,Islamabad,Asia,1.597680e+08,2.358249e+08,2.271967e+08,2.109693e+08,1.944545e+08,1.543699e+08,1.154141e+08,80624057.0,59290872.0,881912.0,267.4018,1.0191,2.96
149,6,NGA,Nigeria,Abuja,Africa,1.398005e+08,2.185412e+08,2.083274e+08,1.839958e+08,1.609529e+08,1.228520e+08,9.521426e+07,72951439.0,55569264.0,923768.0,236.5759,1.0241,2.74